// Vorti qui esas sama en amba lingui aparas sen traduko.
// Vortoj kiuj estas samaj en ambaŭ lingvoj aperas sen traduko.
// Tamen vorti quale "aktoro", "avo" e "bovo" ne esas tote sama, nam en Ido li ne esas maskula o femina.
// Tamen vortoj kiel "aktoro", "avo" kaj "bovo" ne estas tute samaj, char en Ido ili ne estas virseksaj aŭ inseksaj.
// Simbolo "~" indikas traduko ne-exakta
// Simbolo "~" indikas traduko ne-preciza.
// Verbo en Ido finas infinitive per "-ar", en Esperanto per "-i", do hike ni uzas la komuna formo per "-as".
// Verbo en Ido finighas infinitive per "-ar", en Esperanto per "-i", do chi tie ni uzas la komunan formon per "-as".
// Certe ica listo ne esas perfekta, e bezonas plusa laboro, ma ni esperas ke on trovas ol esar utila.
// Certe chi tiu listo ne estas perfekta, kaj bezonas pli da laboro, sed ni esperas ke oni trovas ghin utila.
var vortaroIoEoKruda = {
    "-ab-": "(Sufikso je verbo; ekz.: amabis = estis aminta, amabos = estos aminta)",
    "-ach-": "-aĉ-",
    "-ad-": "",
    "-ag-": "(Sufikso uzata kun substantivo por signifi \"agi per\"; ekz.: martelagas, butonagis)",
    "-aj-": "-aĵ-",
    "-al-": "(Sufikso kun signifo \"rilatanta al\"; ekz. domala, marala, monatala, nacionala)",
    "-ar-": "",
    "-ari-": "(Sufikso por ricevanto de ago; ekz. pagario - tiu kiu ricevas pagon)",
    "-atr-": "(Sufikso kun signifo \"simila a\" aŭ \"kun formo de\"; ekz. metalatra, lanatra)",
    "-e-": "(vidu afiks-liston)",
    "-ebl-": "",
    "-ed-": "(Sufikso por enhavaĵo de; ekz. glasedo; manuedo = manpleno)",
    "-eg-": "",
    "-em-": "",
    "-end-": "",
    "-er-": "(Sufikso por indiki iun aŭ foje ion kiu regule aŭ ofte aŭ tipe faras ion; ekz. fotografero, fumero, prezidero)",
    "-eri-": "(Sufikso por establ(aĵ)o; ekz. lakterio, distilerio, sporterio)",
    "-es-": "-iĝ- (kun verbo; ekz. skribesos = skribiĝos); -ec- [ekz. beleso, infanteso, qualeso = kvalito]",
    "-esk-": "(divenas) -iĝ- [kun adjektivo]; [komencas] ek- [kun verbo]",
    "-esm-": "(Sufikso por indiki numer-vorton ordan; ekz. duesma = dua, unesma = unua)",
    "-estr-": "",
    "-et-": "",
    "-ey-": "-ej-",
    "-i-": "",
    "-id-": "(Sufikso por posteulo; ekz. Izraelido)",
    "-ier-": "(Sufikso kun substantivo); -ul- [iu kiu havas ian atribuon; ekz. milioniero]; -arb- [ekz. pomiero = pomarbo]; -ing- [ekz. plumiero]",
    "-if-": "(Sufikso je substantivo por formi verbon kun senco produkti aŭ eligi; ekz. sangifas, panifo)",
    "-ig-": "",
    "-ik-": "",
    "-il-": "",
    "-im-": "-on-",
    "-in-": "",
    "-ind-": "",
    "-ism-": "",
    "-ist-": "(Sufikso por persono kiu aŭ ĉiam okupiĝas pri io aŭ estas adepto de io; ekz. dentisto, kantisto, pacifisto)",
    "-iv-": "-iv-, povanta (+ verbo)",
    "-iz-": "(Sufikso por formi verbon kun senco \"provizi per\"; ekz. salizas, kronizas)",
    "-op-": "",
    "-opl-": "-obl-",
    "-oz-": "-hav-, -riĉ-, -oz- (Sufikso kun senco \"(en)havanta\"; ekz. poroza, porozeso, marveloza, sukroza)",
    "-ul-": "(Sufikso por virsekso, masklo; ekz. fratulo, kuzulo, bovulo, katulo (virkato))",
    "-un-": "-er-",
    "-ur-": "(Sufikso uzata kun verba radiko por indiki produkton aŭ rezulton; ekz. aperturo, fotografuro, kopiuro, skulturo)",
    "-uy-": "-uj-",
    "Afrik.a": "Afriko",
    "Amerik.a": "Ameriko",
    "Angli.a": "Anglujo, Anglio",
    "Australi.a": "Aŭstralio",
    "Austri.a": "Aŭstrio",
    "Azi.a": "Azio",
    "Belgi.a": "Belgujo, Belgio",
    "Britani.a": "Britujo, Britio",
    "Dani.a": "Danlando, Danujo, Danio",
    "Egipti.a": "Egiptujo, Egiptio",
    "Europ.a": "Eŭropo",
    "Franci.a": "Francujo, Francio",
    "Germani.a": "Germanujo, Germanio",
    "Greki.a": "Grekujo, Grekio",
    "Hispani.a": "Hispanujo, Hispanio",
    "Hungari.a": "Hungarujo, Hungario",
    "Indi.a": "Hindujo, Hindio",
    "Itali.a": "Italujo, Italio",
    "Kanad.a": "Kanado",
    "Kore.a": "Koreujo, Koreo",
    "Nigeri.a": "Niĝerio",
    "Poloni.a": "Pollando, Polujo, Polio",
    "Rusi.a": "Rusujo, Rusio",
    "Us.a": "Usono",
    "a": "al",
    "abad.o": "abato",
    "abandon.as (tr)": "forlasas",
    "abas.as (tr)": "malaltigas; (fig.) malnobligas",
    "abat.as (tr)": "faligas per bato",
    "abdomin.o": "abdomeno",
    "abel.o": "",
    "abism.o": "",
    "ablakt.as (tr)": "demamigas",
    "abolis.as (tr)": "abolicias, abolas",
    "abomin.as (tr)": "abomenas",
    "abon.as": "",
    "abord.as (tr)": "enshipiĝas, entrajniĝas",
    "abort.as": "",
    "aboy.as (netr)": "bojas",
    "abrevi.as (tr)": "mallongigas",
    "abrikot.o": "",
    "abrupt.a": "",
    "absent.a": "forestanta",
    "absolut.a": "",
    "absorb.as (tr)": "sorbas",
    "absten.as (tr)": "abstinas",
    "abstrakt.a": "",
    "absurd.a": "",
    "abund.as (netr)": "estas abunda, abundas",
    "aceler.as (tr)": "akcelas",
    "acend.as (tr)": "fajrigas",
    "acens.as (tr/netr)": "supreniras, *ascendas",
    "acent.o": "akcento",
    "acept.as (tr)": "akceptas",
    "acerb.a": "acida~, acerba~",
    "aces.as (tr)": "havas aliron al",
    "acesor.a": "akcesora",
    "acid.a": "",
    "acident.as (tr)": "kaŭzas akcidenton al",
    "acident.o": "akcidento",
    "ad": "al",
    "ad (= a)": "al",
    "ad.avan.e": "antaŭen",
    "ad.en": "en (+ akuzativo)",
    "ad.junt.as (tr)": "aldonas",
    "ad.maxim.e": "maksimume",
    "ad.minim.e": "minimume",
    "ad.vok.as (tr)": "alvokas",
    "adapt.as": "",
    "adequat.a": "adekvata",
    "adher.as (netr)": "algluiĝas, *adheras",
    "adi.as (tr)": "adiaŭas",
    "adicion.as (tr)": "adicias",
    "adjektiv.o": "",
    "administr.as": "",
    "admir.as": "",
    "admis.as (tr)": "enlasas",
    "adolec.as (netr)": "estas *adoleska",
    "adopt.as": "",
    "ador.as": "",
    "adres.o": "",
    "adult.a": "plenaĝa, *adolta",
    "adulter.as (netr)": "adultas",
    "adverb.o": "",
    "advers.a": "kontraŭa, opona",
    "advokat.o": "",
    "aer.o": "",
    "aeroplan.o": "",
    "afabl.a": "",
    "afanon.o": "enmiksiĝemulo",
    "afecion.as (tr)": "havas korinklinon por",
    "afecion.o": "korinklino",
    "afekt.as (tr)": "afekcias",
    "afektac.as (tr/netr)": "afektas",
    "afer.o": "",
    "afirm.as (tr)": "asertas~, deklaras ke io estas vera",
    "afish.o": "afisho",
    "aflikt.as": "",
    "afrank.as": "",
    "ag.as": "",
    "agent.o": "",
    "agit.as": "",
    "agl.o": "",
    "aglutin.as": "",
    "agnosk.as": "",
    "agnostik.a": "",
    "agost.o": "aŭgusto",
    "agr.o": "kampo",
    "agr.o.kultiv.o": "agrikulturo",
    "agraf.o": "",
    "agreabl.a": "agrabla",
    "agul.o": "kudrilo; nadlo",
    "ajil.a": "movlerta",
    "ajorn.as (tr)": "prokrastas",
    "ajust.as (tr)": "ĝustigas",
    "ajut.o": "",
    "akademi.o": "",
    "akar.o": "",
    "aklam.as": "",
    "akomod.as": "",
    "akompan.as": "",
    "akord.as": "",
    "akordeon.o": "akordiono",
    "akr.a": "akra~; (fig.) amara~ [D sĉarf, herb, beissend [auĉ bildl.], E acrid; acrimonious, F âcre, aigre [pr. et fig.] âcre; mordant, I agro, acre [anĉe fig.], S acre]",
    "akrobat.o": "",
    "akroch.as (tr)": "kroĉas, pendigas je hoko",
    "akt.o": "",
    "aktiv.a": "",
    "aktor.o": "",
    "aktual.a": "",
    "akumul.as": "",
    "akurat.a": "",
    "akustik.o": "",
    "akut.a": "akra; (pri supersigno) dekstrakorna",
    "akuz.as": "",
    "akuzativ.o": "",
    "al (= a la)": "al la",
    "al.o": "flugilo; alo",
    "alarm.as": "",
    "alberg.o": "gastejo, hotelo kampara",
    "album.o": "",
    "albumen.o": "",
    "aleg.as (tr)": "argumentas~, asertas~, donas faktojn aŭ argumentojn por pruvi aŭ pravigi ion",
    "alegori.o": "",
    "alej.as (tr)": "senpezigas",
    "alergi.o": "",
    "alert.a": "vigla",
    "alfabet.o": "",
    "algebr.o": "",
    "ali.o": "ajlo",
    "alini.as (tr)": "liniigas, vicigas",
    "alkohol.o": "",
    "alkov.o": "",
    "almanak.o": "",
    "almon.as (netr)": "donas almozon",
    "alonge": "laŭlonge de",
    "aloy.as (tr)": "alojas",
    "alt.a": "",
    "altar.o": "",
    "alter.as (tr)": "aliigas, shanĝas la naturon aŭ kvaliton de",
    "altern.as": "",
    "alternativ.o": "",
    "altitud.o": "",
    "altr.a": "alia (adj.)",
    "altr.i": "aliaj (pron.)",
    "altr.u": "alia (pron.)",
    "altru.ism.o": "altruismo",
    "altru.ist.o": "altruismulo, altruisto",
    "alud.as": "",
    "alumet.o": "",
    "alumini.o": "",
    "alur.o": "irmaniero, marsh-maniero",
    "am.as": "",
    "amalgam.o": "",
    "amas.o": "",
    "amator.o": "",
    "amb.a": "ambaŭ",
    "ambasad.o": "",
    "ambici.as": "",
    "ambigu.a": "",
    "ambos.o": "",
    "ambulanc.o": "",
    "amelior.as": "plibonigas",
    "amend.o": "monpuno",
    "amfibi.a": "",
    "amik.o": "",
    "amil.o": "amelo",
    "amont.as": "sumiĝas al",
    "amor.as": "",
    "amortis.as (tr)": "amortizas, malintensigas, malfortigas; dampas (muzike); estingas (shuldon)",
    "ampl.a": "pli ol sufiĉa, pli ol sufiĉe granda",
    "ampul.o": "",
    "amput.as": "",
    "amuz.as": "",
    "an": "tuj apud",
    "an-": "",
    "anad.o": "anaso",
    "anagram.o": "",
    "anakronism.o": "",
    "analgezi.as (tr)": "produktas analgezion je",
    "analgezi.o": "",
    "analiz.as": "",
    "analog.a": "",
    "ananas.o": "",
    "anarki.o": "anarĥio, anarkio",
    "anatem.as": "",
    "anatem.o": "",
    "anatomi.o": "",
    "ancestr.o": "praulo, prapatr(in)o",
    "ancien.a": "malnova",
    "anekdot.o": "",
    "anguil.o": "angilo",
    "angul.o": "",
    "anim.as (tr)": "animas; (fig.) vigligas",
    "animal.o": "",
    "aniversari.o": "datreveno",
    "anjel.o": "anĝelo",
    "ank": "ankaŭ",
    "anke": "ankaŭ",
    "ankor-foy.e": "ankoraŭfoje",
    "ankore, ankor": "ankoraŭ, plu",
    "ankr.o": "",
    "anm.o": "animo",
    "anonim.a": "",
    "anorak.o": "",
    "ans.o": "",
    "antagonism.o": "",
    "antagonist.o": "",
    "ante": "antaŭ (en tempo)",
    "ante.a": "antaŭa",
    "anten.o": "",
    "anter.o": "",
    "anti-": "(Prefikso kun senco \"kontraŭ\", uzata ĉefe en sciencaj vortoj; ekz. antisepta)",
    "anticip.as": "",
    "antidot.o": "",
    "antilop.o": "",
    "antiqu.a": "antikva",
    "antologi.o": "",
    "anunc.as (tr)": "anoncas",
    "anxi.as (netr)": "maltrankvilas",
    "apar.as (netr)": "aperas",
    "aparat.o": "",
    "apart.a": "",
    "apartament.o": "",
    "aparten.as": "",
    "apati.o": "",
    "apel.as (netr)": "apelacias, apelas",
    "apendic.o": "",
    "apene, apen": "apenaŭ",
    "apert.as (tr)": "malfermas",
    "apetit.as (tr)": "havas apetiton por",
    "apetit.o": "",
    "aplast.as (tr)": "(kun)premegas (ion ne rezistpovan)",
    "aplaud.as (tr)": "aplaŭdas",
    "aplik.as": "",
    "apog.as": "",
    "apokrif.a": "",
    "apostol.o": "",
    "apostrof.o": "",
    "apotek.o": "",
    "apreci.as (tr)": "taksas alte, aprecas, aprezas",
    "aprentis.o": "metilernanto",
    "april.o": "",
    "aprob.as": "",
    "aproxim.as": "proksimumigas",
    "apt.a": "taŭga",
    "apud": "",
    "apud.a": "",
    "apunt.as (tr)": "celumas",
    "aqu.o": "akvo",
    "aquari.o": "akvario",
    "aquir.as (tr)": "akiras",
    "arach.as (tr)": "elshiras, fortiras",
    "arane.o": "",
    "aranj.as (tr)": "aranĝas",
    "arbitr.as (tr)": "arbitracias",
    "arbor.o": "arbo",
    "arbust.o": "",
    "arch.o": "arkeo",
    "ardez.o": "",
    "ardor.as (netr)": "ardas",
    "ardu.a": "malglata, sulka, peniga",
    "are.o": "",
    "aren.o": "",
    "arest.as": "",
    "argan.o": "simpla argano, levbumo",
    "argil.o": "",
    "argument.as": "",
    "ari.o": "",
    "arid.a": "seka kaj malfekunda",
    "arist.o": "",
    "aristokrat.a": "",
    "aritmetik.o": "",
    "ariv.as (netr)": "alvenas",
    "arjent.o": "arĝento",
    "ark.o": "",
    "arkad.o": "arkadaro",
    "arkaik.a": "",
    "arkeolog.o": "",
    "arkeologi.o": "",
    "arki-": "arĥi-, arki-",
    "arkitekt.o": "",
    "arkitektur.o": "",
    "arkiv.o": "",
    "arlekin.o": "arlekeno",
    "arm.o": "armilo",
    "arme.o": "",
    "armor.o": "shranko",
    "arog.as": "",
    "arom.o": "",
    "aroz.as (tr)": "malsekigas, humidigas",
    "art.o": "",
    "arteri.o": "",
    "artific.o": "artefaritaĵo, artifiko~",
    "artik.o": "",
    "artikl.o": "",
    "artizan.o": "metiisto, manlaboristo",
    "artrit.o": "",
    "asalt.as (tr)": "kuratakas",
    "asbest.o": "",
    "asekur.as": "",
    "asembl.as (tr)": "kunigas, kunvenigas",
    "asent.as (tr)": "jesas",
    "asept.a": "asepsa",
    "asert.as": "",
    "asfalt.o": "",
    "asidu.a": "konstanta (pri laboro ktp)",
    "asiej.as (tr)": "sieĝas",
    "asign.as": "",
    "asimil.as": "",
    "asist.as (tr)": "ĉeestas",
    "askolt.as (tr)": "aŭskultas",
    "asn.o": "azeno",
    "asoci.as": "",
    "asort.as (tr)": "sortimentas",
    "asparag.o": "",
    "aspekt.as": "",
    "asper.a": "malglata",
    "aspir.as": "",
    "aspirin.o": "",
    "asterisk.o": "steleto, asterisko",
    "astm.o": "",
    "aston.as (tr)": "mirigas",
    "astr.o": "",
    "astronom.o": "",
    "astronomi.o": "",
    "asum.as (tr)": "sharĝas sin per, alprenas",
    "atach.as (tr)": "alligas, alfiksas",
    "atak.as": "",
    "ateism.o": "",
    "ateist.o": "",
    "atelier.o": "laborejo (de artisto aŭ metiisto)",
    "atenc.as (tr)": "atentas",
    "atent.as (tr)": "atakas krime, atencas",
    "atest.as": "",
    "ating.as": "",
    "atitud.o": "sinteno",
    "atlas.o": "maparo",
    "atlet.o": "",
    "atmosfer.o": "",
    "atom.o": "",
    "atrakt.as": "",
    "atrap.as (tr)": "trompas~, prifriponas~",
    "atribu.as": "",
    "atribut.o": "",
    "atun.o": "tinuso",
    "aturd.as (tr)": "senkonsciigas",
    "aucion.as (tr)": "ofertas pli altan prezon",
    "aud.as (tr)": "aŭdas",
    "audac.as (tr)": "aŭdacas",
    "augment.as (tr/netr)": "pliigas, plimultigas",
    "augur.as (tr)": "aŭguras",
    "august.a": "respekteginda, majesta",
    "aul.o": "aŭlo",
    "aureol.o": "aŭreolo, nimbo",
    "auror.o": "tagiĝo, aŭroro",
    "auspici.o": "aŭspicio",
    "auster.a": "severmora (pri si)",
    "autentik.a": "aŭtenta, aŭtentika",
    "autobiografi.o": "aŭtobiografio",
    "autobus.o": "aŭtobuso, buso",
    "autograf.o": "aŭtografo",
    "autokrat.o": "aŭtokrato",
    "automat.a": "aŭtomata",
    "automobil.o": "aŭtomobilo",
    "autonom.a": "aŭtonoma",
    "autor.o": "aŭtoro",
    "autoritat.o": "aŭtoritato",
    "autun.o": "aŭtuno",
    "av.o": "",
    "avan": "antaŭ (en spaco)",
    "avanc.as (tr/netr)": "antaŭeniras",
    "avantaj.o": "avantaĝo",
    "avantal.o": "antaŭtuko",
    "avar.a": "avida",
    "avelan.o": "avelo",
    "aven.o": "",
    "aventur.as (netr)": "serĉas aŭ iras aventure",
    "aventur.o": "",
    "avenu.o": "",
    "averaj.o": "averaĝo",
    "avers.o": "bildoflanko~, malo de dorsa flanko",
    "avert.as": "",
    "aviac.as (netr)": "flugas (en flug-mashino)",
    "avid.a": "",
    "aviz.as": "",
    "ax.o": "akso",
    "axiom.o": "aksiomo",
    "aye!": "aj!, aŭ!, huj! (ekkrio pro subita doloro; D autsĉ, E ouĉ, ow, F aïe, I ahi, S ay)",
    "azil.o": "",
    "babil.as": "",
    "bagaj.o": "pakaĵ(ar)o",
    "bagatel.o": "",
    "bak.as": "",
    "bal.o": "",
    "balanc.o": "pesilo (ekvilibra)",
    "balay.as (tr)": "balaas",
    "bald.e": "baldaŭ",
    "balen.o": "",
    "balet.o": "baledo",
    "balkon.o": "",
    "baln.as (tr)": "banas",
    "balon.o": "sfero (plena je aero), balono",
    "balustrad.o": "",
    "bambu.o": "",
    "banan.o": "",
    "band.o": "grupo (de personoj), bando~",
    "bandaj.o": "bandaĝo; pneŭmatiko",
    "bandit.o": "",
    "bank.o": "",
    "bankrot.as": "",
    "bapt.as": "",
    "bar.as": "",
    "barakt.as": "",
    "barb.o": "",
    "barbar.a": "",
    "barel.o": "",
    "barikad.o": "",
    "bark.o": "",
    "barok.a": "bizara",
    "bas.a": "malalta, *basa",
    "basen.o": "",
    "bask.o": "",
    "baskul.as": "",
    "bastion.o": "",
    "baston.o": "",
    "bat.as": "",
    "batali.as (netr)": "batalas",
    "batel.o": "boato",
    "bateri.o": "",
    "bay.o": "golfeto",
    "baz.o": "",
    "bazar.o": "",
    "be.as (netr)": "gapas~",
    "beat.a": "",
    "bebe.o": "bebo",
    "bed.o": "",
    "bej.a": "flavgriza",
    "bek.o": "",
    "bel.a": "",
    "bend.o": "strio, bendo~",
    "benedik.as (tr)": "benas",
    "benign.a": "favora; milda, *benigna",
    "benk.o": "",
    "benzin.o": "benzeno",
    "ber.o": "",
    "bered.o": "ĉapo (vaska)",
    "berjer.o": "brakseĝo remburita",
    "berlok.o": "breloko",
    "bers.as (tr)": "lulas",
    "besti.o": "besto",
    "bet.o": "beto (en pli ĝenerala senco)",
    "beton.o": "",
    "betrav.o": "(ruĝa) beto",
    "bezon.as": "",
    "bi-": "(Prefikso ĉefe scienca kun senco \"du\"; ekz. biplano)",
    "bi.punt.o": "dupunkto",
    "bibl.o": "biblio",
    "bibliotek.o": "",
    "bicikl.o": "",
    "bidet.o": "bideo",
    "bidon.o": "ladskatolo (por oleo ktp)",
    "bifurk.as": "branĉiĝas, forkiĝas",
    "bigot.a": "",
    "bilanc.o": "",
    "biliet.o": "bileto",
    "bind.as": "",
    "binet.o": "sarkilo~ (D Hacke, E hoe, F binette, I zappa, S binadera)",
    "binokl.o": "okulvitroj",
    "biografi.o": "",
    "bir.o": "biero",
    "bis": "",
    "biskot.o": "",
    "bisquit.o": "biskvito",
    "bitr.a": "amara",
    "blam.as (tr)": "kulpigas",
    "blank.a": "",
    "blasfem.as": "",
    "blind.a": "",
    "blok.o": "",
    "blokus.as (tr)": "blokadas",
    "blond.a": "",
    "blotis.as (netr)": "kaŭras~, kuntiras sin",
    "blu.a": "",
    "bluf.as": "",
    "bluz.o": "",
    "bo-": "",
    "bobin.o": "bobeno",
    "boikot.as (tr)": "bojkotas",
    "bok.o": "busho",
    "bol.o": "bovlo, pelvo",
    "boli.as (netr)": "bolas",
    "bomb.o": "",
    "bon.a": "",
    "bon.ven.ig.as": "",
    "bonbon.o": "bombono",
    "bonet.o": "ĉapo",
    "bor.as": "",
    "bord.o": "rando",
    "bord.um.o": "tekseĝo, (drap)randaĵo",
    "bosk.o": "arbareto, bosko~",
    "bot.o": "",
    "botel.o": "",
    "bov.o": "",
    "bracelet.o": "",
    "braki.o": "brako",
    "bram.as (netr)": "blekas",
    "branch.o": "branĉo",
    "brandis.as (tr)": "svingas~",
    "branki.o": "branko",
    "bras.as (tr)": "kirlas",
    "brav.a": "",
    "brech.o": "breĉo",
    "bretel.o": "skarpo~ ;shelko, -eto",
    "brez.o": "lignocindro~, ligno shanĝita al karbono per brulo",
    "brid.o": "",
    "brik.o": "",
    "bril.as": "",
    "brisk.a": "vigla~, verva~",
    "briz.o": "fresha vento, *brizo",
    "broch.o": "broĉo",
    "brodkast.as": "dissendas, disaŭdigas",
    "brokant.as": "",
    "bronz.o": "",
    "bros.as": "",
    "bros.il.o": "broso",
    "brosh.as (tr)": "kudras (librojn)",
    "brov.o": "",
    "bruet.o": "ĉarumo",
    "bruis.as (netr)": "bruas",
    "brul.as": "",
    "brun.a": "",
    "brusk.a": "",
    "brut.o": "",
    "bub.o": "bubo; (ludkarto) pajo",
    "buch.as (tr)": "buĉas",
    "bud.as (netr)": "paŭtas",
    "budjet.o": "buĝeto, budĝeto",
    "buf.as (netr)": "shvelas",
    "bufet.o": "bufedo",
    "bufon.o": "histriono, arlekenaĉo",
    "buji.o": "vakskandelo; sparkilo",
    "buket.o": "bukedo",
    "bukl.o": "buko",
    "bul.o": "pilko",
    "bulb.o": "",
    "buletin.o": "bulteno",
    "burjon.o": "burĝono",
    "burokrat.o": "",
    "burs.o": "monujo (posha)",
    "bush.o": "densejo, arbetaro",
    "busol.o": "kompaso",
    "but.as (netr)": "frapas hazarde (ekz. per piedo)",
    "butik.o": "",
    "buton.o": "",
    "butr.o": "butero",
    "bux.o": "skatolo",
    "ca (= ica)": "ĉi tiu, tiu ĉi (adj.)",
    "ced.as": "",
    "cel.as (tr)": "kashas",
    "celebr.as (tr)": "festas, solenas, celebras",
    "celeri.o": "",
    "celib.a": "fraŭla",
    "celul.o": "ĉelo",
    "cement.o": "",
    "cen.o": "sceno",
    "censur.as (tr)": "cenzuras",
    "cent": "",
    "centi-": "",
    "centr.o": "",
    "ceramik.o": "",
    "cereal.o": "",
    "cerebr.o": "cerbo",
    "ceremoni.o": "",
    "ceriz.o": "ĉerizo",
    "cert.a": "certa~",
    "certen.a": "iu~, ia~, certa~ (D ein gewisser, E a certain)",
    "certifik.as (tr)": "atestas kiel aŭtenta",
    "cerv.o": "",
    "ces.as (tr/netr)": "ĉesas",
    "ceter.o": "",
    "chagren.as (netr)": "malĝojas (ntr), ĉagrenas [tr]",
    "chambr.o": "ĉambro",
    "champinion.o": "fungo manĝebla, *shampinjono",
    "champion.o": "ĉampiono",
    "chanc.o": "shanco",
    "chanj.as (tr/netr)": "shanĝas",
    "chant.o": "mallarĝa flanko (de io larĝa en aliaj direktoj, ekz. libro)",
    "chapel.o": "ĉapelo",
    "chapitr.o": "ĉapitro",
    "char.o": "ĉaro",
    "chariot.o": "sharĝaŭto (kun flank-tabuloj)",
    "charj.as (tr)": "sharĝas",
    "charm.as (tr)": "ĉarmas",
    "charnir.o": "ĉarniro",
    "chas.as (tr)": "ĉasas",
    "chast.a": "ĉasta",
    "che": "ĉe la hejmo de",
    "chef.a": "ĉefa",
    "chek.o": "ĉeko",
    "cher.a": "multekosta",
    "chip.a": "malmultekosta",
    "chokolad.o": "ĉokolado",
    "chose.o": "shoseo; digvojo",
    "cidr.o": "",
    "ciel.o": "ĉielo",
    "cienc.o": "scienco",
    "cifr.o": "cifero",
    "cigan.o": "",
    "cign.o": "",
    "cikatr.o": "",
    "cikl.o": "",
    "ciklon.o": "",
    "cilindr.o": "",
    "cindr.o": "",
    "cinem.o": "kinejo",
    "cinik.o": "cinikulo",
    "cintil.o": "fajrero",
    "cintil.o (elektr.al.a)": "sparko",
    "cirk.o": "",
    "cirkl.o": "",
    "cirkond.as (tr)": "ĉirkaŭas",
    "cirkonspekt.a": "singarda~, malriskema~",
    "cirkonstanc.o": "",
    "cirkuit.o": "rondiro, ĉirkaŭiro; (elektro) cirkvito",
    "cirkul.as": "",
    "cirkuler.o": "",
    "cirkum": "ĉirkaŭ (prep.)",
    "cirkum.e": "ĉirkaŭ (adv.)",
    "cit.as": "",
    "civil.a": "",
    "civiliz.as": "",
    "civiliz.es.o": "civilizacio",
    "civit.o": "",
    "ciz.o": "tondilo",
    "cizel.as (tr)": "ĉizas",
    "co (= ico)": "ĉi tio, tio ĉi",
    "da": "de (indikante aganton), far*",
    "dal": "de~ la",
    "dam.o": "virino (edziniĝinta aŭ vidvino)",
    "damn.as": "",
    "damzel.o": "fraŭlino",
    "danjer.o": "danĝero",
    "dank.as": "",
    "dans.as (tr/netr)": "dancas",
    "dard.o": "mansago, sageto; pikilo (de insekto)",
    "darf.as (netr)": "havas rajton aŭ permeson",
    "darn.as (tr)": "riparas nur kudre (vestojn)",
    "dat.o": "",
    "dazl.as (tr)": "blindumas, blindetigas",
    "de": "de, da (indikante originon, devenon, enhavon aŭ kvanton)",
    "de.o": "dio",
    "de.pos": "depost, ekde",
    "deb.as (tr)": "shuldas",
    "debat.as": "",
    "debet.o": "",
    "dec.as": "",
    "decembr.o": "",
    "decens.as (tr/netr)": "malsupreniras, *descendas",
    "decept.as (tr)": "trompas la esperojn de, *desapontas (D enttäusĉen, E disappoint, F décevoir, I deludere, S decepcionar)",
    "decid.as": "",
    "decimal.a": "",
    "dedik.as (tr)": "dediĉas",
    "dedukt.as": "",
    "defekt.o": "neperfektaĵo",
    "defens.as (tr)": "defendas",
    "defi.as": "",
    "deficit.o": "",
    "defin.as (tr)": "difinas",
    "definitiv.a": "",
    "deform.as (tr)": "misformas, de-formas",
    "degener.as": "",
    "degn.as (netr)": "bonvolas~, *degnas",
    "dejun.as (netr)": "tagmanĝas",
    "dejur.as (netr)": "deĵoras",
    "dek": "",
    "dekad.as (netr)": "malpliboniĝas",
    "deklar.as": "",
    "dekor.as (tr)": "dekoracias",
    "del": "de~ la",
    "deleg.as (tr)": "delegacias, (delegas)",
    "delegacion.o": "delegacio",
    "delekt.as (tr)": "ravas",
    "deliber.as (netr)": "konsideradas",
    "delici.o": "ĝuo bonega",
    "delikat.a": "delikata~",
    "delikt.as (netr)": "faras delikton",
    "delikt.o": "",
    "delt.o": "",
    "demand.as (tr)": "petas (ion de iu)",
    "demarsh.as (netr)": "klopodas",
    "dement.a": "freneza",
    "dementi.as (tr)": "dementas",
    "demision.as (netr)": "eksiĝas",
    "demokrat.a": "",
    "demokrati.o": "",
    "demolis.as (tr)": "malkonstruas",
    "demon.o": "",
    "demonstr.as (tr)": "demonstracias, demonstras",
    "denigr.as (tr)": "nigrigas, malestimigas",
    "dens.a": "",
    "dent.o": "",
    "dentel.o": "punto",
    "denunc.as": "",
    "depart.as (netr)": "foriras",
    "depend.as": "",
    "depoz.as (tr)": "deponas",
    "depres.as (tr)": "premas malsupren; deprimas",
    "deriv.as": "",
    "des-": "mal-",
    "des.apar.as (netr)": "malaperas, svenas~",
    "des.avantaj.o": "malavantaĝo",
    "des.facil.a": "malfacila",
    "des.kovr.as (tr)": "malkovras, eltrovas",
    "des.quiet.a": "maltrankvila",
    "desegn.as": "",
    "deser.o": "deserto",
    "desert.as (tr)": "dizertas; forlasas",
    "deskript.as (tr)": "vortpentras, priskribas",
    "despens.o": "manĝaĵejo",
    "destin.as": "",
    "destrukt.as (tr)": "detruas",
    "detal.o": "",
    "detal.oz.a": "detala",
    "detektiv.o": "",
    "determin.as": "",
    "deters.as (tr)": "purigas, *detergas",
    "detriment.as (tr)": "estas malprofita al",
    "dev.as (netr)": "devas morale",
    "dev.o": "",
    "devanc.as (tr)": "preterpasas~, *devancas",
    "develop.as (tr)": "disvolvas, evoluigas",
    "deviac.as": "devias",
    "devot.a": "sindona",
    "dextr.a": "dekstra",
    "dezert.a": "",
    "dezir.as": "",
    "dezol.as (tr)": "malĝojigas, afliktas",
    "di": "de (indikante proprieton, ian rilaton aŭ genitivon)",
    "di qua": "kies",
    "di qui": "kies",
    "di.-mez.o": "tagmezo",
    "di.o": "tago~ (24 horoj), diurno",
    "diabl.o": "",
    "diafan.a": "travidebla",
    "diagnoz.as": "",
    "diagonal.a": "",
    "diagram.o": "",
    "dialekt.o": "",
    "diamant.o": "",
    "diametr.o": "",
    "diari.o": "taglibro",
    "dic.as (tr)": "diras",
    "dicern.as (tr)": "distingas",
    "dicionari.o": "vortaro (alfabeta kun difinoj)",
    "diciplin.as": "",
    "dicipul.o": "disĉiplo",
    "diet.o": "",
    "difam.as (tr)": "atakas la honoron aŭ reputacion de",
    "difer.as (netr)": "diferencas",
    "difuz.as": "",
    "dig.o": "",
    "digest.as": "",
    "dign.a": "inda, meritplena",
    "digres.as (netr)": "deflankiĝas",
    "dik.a": "",
    "diktator.o": "",
    "dil": "de~ la",
    "dilem.o": "",
    "diligent.a": "",
    "dilut.as (tr)": "diluas",
    "dimension.o": "dimensio",
    "diminut.as (tr/netr)": "malgrandigas, -iĝas",
    "din.a": "maldika",
    "dind.o": "meleagro",
    "dine.as (netr)": "vespermanĝas",
    "diplom.o": "",
    "direcion.o": "direkto~ (A-B kaj B-A)",
    "direkt.as": "",
    "diret.a": "senpera",
    "dis-": "",
    "dis.solv.as (tr)": "disigas, solvas~",
    "dish.o": "manĝaĵo preparita, plado~",
    "disip.as": "",
    "disk.o": "",
    "diskont.as": "",
    "diskret.a": "",
    "diskurs.as (netr)": "donas diskurson, paroladas",
    "diskurs.o": "",
    "diskut.as": "",
    "dispers.as": "",
    "dispon.as": "",
    "disput.as": "",
    "dist.ant.a": "malproksima",
    "dist.as (netr)": "estas malproksima",
    "dist.o": "distanco",
    "disting.as (tr)": "diferencigas",
    "distint.a": "aparta~, klara~ (D deutliĉ, EF distinct, IS distinto)",
    "distrakt.as (tr)": "distras",
    "distribut.as (tr)": "distribuas",
    "distrikt.o": "",
    "diten.as (tr)": "retenas (ĝis iu okazo)",
    "ditres.o": "aflikto, malĝojo~",
    "diven.as (tr/netr)": "fariĝas, iĝas",
    "diverg.as": "disiĝas, (mat., fiz.) diverĝas",
    "divers.a": "",
    "divid.as": "",
    "divin.as (tr)": "divenas",
    "divulg.as (tr)": "malkashas (sekreton ktp)",
    "dizastr.o": "katastrofo kiu afliktas multnombre",
    "do": "",
    "doc.as (tr)": "instruas (temon)",
    "docil.a": "obeema, kvieta~",
    "dogan.o": "",
    "dogmat.o": "dogmo",
    "dok.o": "",
    "doktor.o": "",
    "dokument.o": "",
    "dolc.a": "dolĉa",
    "dolor.as": "",
    "dom.o": "",
    "domaj.as (tr)": "difektas, damaĝas",
    "domen.o": "bieno; sfero de ago aŭ influo",
    "domestik.a": "(pri animalo) hejma~, loĝanta kun homoj",
    "dominac.as (tr)": "dominas",
    "domt.as (tr)": "subjugigas",
    "don.as": "",
    "donac.as": "",
    "dop": "malantaŭ (en spaco)",
    "dorlot.as": "",
    "dorm.as": "",
    "dorn.o": "",
    "dors.o": "",
    "dot.as": "",
    "dramat.o": "dramo",
    "drash.as (tr)": "drashas",
    "drastik.a": "drasta",
    "drift.as (netr)": "drivas",
    "dril.o": "",
    "drink.as (tr)": "trinkas",
    "drog.o": "",
    "drol.a": "amuza~, komika~",
    "dron.as (tr)": "dronigas",
    "du": "",
    "du.a-dek": "dudek",
    "du.esm.a": "dua",
    "du.im.o": "duono",
    "du.opl.a": "duobla",
    "dubit.as (netr)": "dubas",
    "dukt.as (tr)": "kondukas",
    "dum": "",
    "dum ke": "dum, dum ke",
    "dung.o": "sterko",
    "dup.o": "trompito naiva",
    "duplikat.o": "",
    "dur.as (netr)": "daŭras",
    "durst.as (netr)": "soifas",
    "dush.as (tr)": "dushas",
    "e": "kaj",
    "e.c. (= ed cetere)": "k.t.p., ktp",
    "ebri.a": "",
    "ecel.ant.a": "bonega~",
    "ecel.as (netr)": "estas bonega, superas",
    "ecept.as (tr)": "esceptas",
    "eces.as (tr/netr)": "havas eksceson",
    "echop.o": "budo",
    "ecit.as (tr)": "ekscitas",
    "ed (= e)": "kaj",
    "edc": "ktp",
    "edit.as (tr)": "eldonas",
    "eduk.as": "",
    "efac.as (tr)": "forvishas, malaperigas~",
    "efekt.o": "",
    "efemer.a": "",
    "eficient.a": "*rendimenta",
    "efik.as": "",
    "eg.o.ist.a": "egoista",
    "egal.a": "",
    "egar.as (tr)": "mislokas, perdetas",
    "egard.as (tr)": "enkalkulas, atentas",
    "ek": "el",
    "ek.o": "eĥo",
    "eklezi.o": "",
    "ekonomi.o": "",
    "el (= elu)": "shi",
    "elabor.as (tr)": "ellaboras",
    "elastik.a": "elasta",
    "elefant.o": "",
    "elegant.a": "",
    "elekt.as": "",
    "elektr.o": "",
    "elektronik.o": "",
    "element.o": "",
    "elev.as (tr)": "plialtigas",
    "elimin.as": "",
    "eloquent.a": "elokventa",
    "elu (= el)": "shi",
    "elu.a": "shia",
    "emali.o": "emajlo",
    "embaras.as": "",
    "emblem.o": "",
    "embrac.as (tr)": "ĉirkaŭprenas, stringas",
    "embusk.as": "",
    "emend.as (tr)": "amendas",
    "emfaz.as": "",
    "eminent.a": "",
    "emis.as (tr)": "eligas, emisias",
    "emoc.as (netr)": "emociiĝas",
    "emplastr.o": "pretpansaĵo",
    "employ.as (tr)": "okupigas",
    "emund.as (tr)": "pritondas, ĉirkaŭtranĉas",
    "en": "",
    "en.ir.as": "",
    "en.ter.ig.as": "",
    "endetal.a": "podetala",
    "enemik.o": "malamiko",
    "energi.o": "",
    "engaj.as (tr)": "dungas",
    "engros.a": "pogranda",
    "enigmat.o": "enigmo",
    "enorm.a": "grandega",
    "enoy.as (netr)": "enuas",
    "enrejistr.as (tr)": "registras",
    "ensembl.o": "",
    "ent.o": "",
    "entern.as (tr)": "internigas",
    "entraprez.as (tr)": "entreprenas",
    "entrav.as (tr)": "katenas",
    "entuziasm.as (netr)": "estas entuziasma",
    "entuziasm.o": "",
    "envelop.as (tr)": "envolvas",
    "envidi.as (tr)": "envias",
    "episkop.o": "",
    "epizod.o": "",
    "epok.o": "",
    "equator.o": "ekvatoro",
    "equilibr.as (tr/netr)": "ekvilibras",
    "equip.as (tr)": "ekipas",
    "equival.as (tr)": "egalvaloras",
    "er.o": "erao",
    "erekt.as (tr)": "starigas (vertikale)",
    "erik.o": "",
    "ermit.o": "",
    "erod.as (tr)": "erozias",
    "eror.as (netr)": "eraras",
    "erste": "ne antaŭ (pri tempo)",
    "erupt.as (netr)": "erupcias, (eruptas)",
    "es (= es.as)": "estas",
    "es.as (netr)": "estas",
    "esam.o": "svarmo",
    "esenc.o": "",
    "esforc.as (netr)": "penas",
    "eskald.as (tr)": "brogas",
    "eskaler.o": "shtuparo",
    "eskap.as": "",
    "eskarp.a": "kruta",
    "eskombr.o": "forĵetaĵo, rubo",
    "eskrok.as (tr)": "friponas~, shtelas per trompo aŭ ruzo",
    "eskudel.o": "supplado",
    "espad.o": "glavo",
    "esper.as": "",
    "esprit.o": "sprit(ec)o",
    "esquad.o": "roto; grupo (de laboristoj); teamo",
    "est.o": "oriento",
    "establis.as (tr)": "establas",
    "estim.as": "",
    "esvan.as (netr)": "svenas~",
    "etaj.o": "etaĝo",
    "etap.as (netr)": "haltas je etapo",
    "etern.a": "",
    "etik.o": "",
    "etiket.o": "etikedo",
    "etuy.o": "ujo speciala por iu entenaĵo (ekz. violono)",
    "eufemism.o": "eŭfemismo",
    "ev.as (tr)": "aĝas",
    "ev.o": "aĝo",
    "evalu.as (tr)": "taksas",
    "event.as (netr)": "okazas",
    "event.o": "okazo",
    "eventual.a": "",
    "evident.a": "",
    "evier.o": "(lavo)pelvo, defluejo (kiel en kuirejo)",
    "evit.as": "",
    "ex-": "eks-",
    "exajer.as": "troigas",
    "exakt.a": "preciza; (matematiko) ekzakta",
    "examen.as (tr)": "ekzamenas",
    "exasper.as (tr)": "kolerigas~, iritas~ (E exasperate, F exaspérer, I esasperare, S exasperar)",
    "exekut.as (tr)": "ekzekucias",
    "exempl.o": "",
    "exempler.o": "ekzemplero",
    "exerc.as (tr)": "ekzercas",
    "exhaust.as (tr)": "elĉerpas, elkonsumas; ellacigas",
    "exhort.as (tr)": "admonas~",
    "exist.as (netr)": "ekzistas",
    "exkav.as (tr)": "elfosas, elkavigas",
    "exkluz.as (tr)": "elbaras, ekskluzivas",
    "exkurs.as (netr)": "ekskursas",
    "exkuz.as (refl)": "senkulpigas",
    "exotik.a": "ekzotika",
    "expans.as (tr/netr)": "pligrandigas, -iĝas, ekspansias",
    "expedi.as (tr)": "ekspedas",
    "expedicion.o": "ekspedicio",
    "expekt.as (tr)": "atendas~, antaŭvidas~, supozas~ (D erwarten, E expect, F s'attendre à, I aspettarsi)",
    "experienc.as (tr)": "spertas",
    "experiment.as (tr/netr)": "eksperimentas",
    "expert.a": "sperta",
    "explik.as (tr)": "klarigas",
    "explor.as (tr)": "esploras",
    "explot.as (tr)": "ekspluatas",
    "exploz.as (netr)": "eksplodas",
    "expoz.as (tr)": "elmontras, ekspozicias",
    "expres.as (tr)": "esprimas",
    "extens.as (tr)": "etendas",
    "exter": "ekster",
    "exting.as (tr/netr)": "estingas",
    "extrakt.as (tr)": "ekstraktas",
    "extraordinar.a": "eksterordinara",
    "extrem.a": "ekstrema",
    "fab.o": "",
    "fabl.o": "",
    "fabrik.as": "",
    "fac.as (tr)": "faras",
    "facet.o": "",
    "facil.a": "",
    "facin.as (tr)": "fascinas",
    "fair.o": "fajro",
    "fak.o": "",
    "fakt.o": "",
    "faktor.o": "",
    "faktur.o": "",
    "fakultativ.a": "",
    "fal.as": "",
    "falch.as (tr)": "falĉas",
    "fald.as": "",
    "falen.o": "nokta papilio, *faleno~",
    "fali.as (tr/netr)": "malsukcesas, fiaskas~",
    "fals.a": "",
    "fam.o": "",
    "fam.oz.a": "fama, fame konata, renoma",
    "famili.o": "",
    "familiar.a": "",
    "famin.o": "malsatego",
    "fanatik.a": "",
    "fanfaron.as": "",
    "fang.o": "koto",
    "fantom.o": "",
    "farb.o": "",
    "fard.o": "shminko",
    "farin.o": "faruno",
    "faring.o": "",
    "farmaci.o": "",
    "fasad.o": "",
    "fask.o": "",
    "fason.as (tr)": "formas; fasonas",
    "fat.o": "sorto",
    "fatig.as (tr)": "lacigas",
    "favor.as": "",
    "faz.o": "",
    "fe.o": "",
    "febl.a": "malforta",
    "febr.as": "",
    "februar.o": "",
    "feder.as (tr)": "federacias, (federas)",
    "fel.o": "",
    "felg.o": "rando (de rado), radrondo",
    "felic.a": "feliĉa",
    "femin.a": "ina, inseksa, ingenra",
    "femur.o": "femurosto",
    "fen.o": "fojno",
    "fenc.o": "barilo~ (D Zaun, E fence, F barrière~, I recinto~, S valla, cerca)",
    "fend.as": "",
    "fenestr.o": "",
    "fenomen.o": "",
    "fer.o": "",
    "ferdek.o": "",
    "feri.o": "foiro",
    "ferm.a": "firma",
    "feroc.a": "kruela~",
    "fertil.a": "fekunda (produkta)",
    "fervor.as": "",
    "fest.as (netr)": "solenas; celebras",
    "festin.as": "festenas",
    "fianc.as (tr)": "fianĉigas",
    "fiask.o": "",
    "fibr.o": "",
    "fid.as": "",
    "fidel.a": "",
    "fier.a": "",
    "figur.o": "",
    "fiktiv.a": "",
    "fil.o": "fadeno",
    "fili.in.o": "filino",
    "fili.o": "filo aŭ filino",
    "fili.ul.o": "filo",
    "film.o": "",
    "filtr.as": "",
    "fin.al.a": "fina",
    "fin.as (tr/netr)": "finas, -iĝas",
    "fing.as (tr)": "shajnigas~ (D vortäusĉen, E feign, sham, F feindre, I fingere~, S fingir)",
    "fingr.o": "",
    "fint.as": "",
    "firm.o": "firmao, firmo, negoco~",
    "fish.o": "fisho",
    "fit.as (netr)": "bone sidas (en), estas laŭmezura",
    "fix.a": "fiksita",
    "flak.o": "pluvkaveto, *flako",
    "flam.o": "",
    "flank.o": "flanko~",
    "flar.as": "",
    "flat.as": "",
    "flav.a": "",
    "flech.o": "sago",
    "fleg.as": "",
    "flex.as (tr/netr)": "fleksas, -iĝas",
    "flirt.as (netr)": "flirtas~, koketas",
    "flok.o": "",
    "flor.o": "",
    "flos.o": "naĝilo",
    "flotac.as (netr)": "flosas",
    "flu.as": "",
    "flug.as": "",
    "fluid.a": "",
    "fluktu.as": "",
    "flur.o": "intershtuparo",
    "fluvi.o": "granda rivero",
    "fok.o": "fokuso",
    "fol.a": "freneza",
    "foli.et.o": "flugfolio",
    "foli.o": "",
    "fond.as": "",
    "font.o": "",
    "fonten.o": "fontano",
    "for": "for de",
    "for.a": "",
    "for.e": "for",
    "forc.o": "forto",
    "forest.o": "arbarego",
    "forj.as (tr)": "forĝas",
    "fork.o": "",
    "form.al.a": "formala",
    "form.o": "",
    "formac.as (tr)": "formas",
    "format.o": "",
    "formik.o": "",
    "formul.o": "",
    "formulari.o": "formularo",
    "forn.o": "bakujo",
    "fors.as (tr)": "perfortas~ (D zwingen, aufbreĉen, E force, F forcer, I forzare, S forzar~)",
    "forsan": "eble~ (D vielleiĉt, E perhaps, F peut-être, I forse)",
    "fort.a": "",
    "fortifik.as (tr)": "fortikigas",
    "fortun.o": "bonshanco",
    "fortun.oz.a": "bonshanca",
    "fos.o": "fosaĵo",
    "fosat.o": "fosaĵo, ĉirkaŭfosaĵo",
    "fost.o": "",
    "fotel.o": "brakseĝo, (fotelo~)",
    "fotograf.as": "",
    "fotokopi.as": "",
    "foy.o": "fojo",
    "fracion.o": "frakcio",
    "frag.o": "",
    "fragment.o": "",
    "frajil.a": "rompiĝema, facile rompebla",
    "frakas.as": "",
    "fram.o": "framo; ĉasio",
    "framb.o": "",
    "frap.as": "",
    "frat.in.o": "",
    "frat.o": "frato aŭ fratino",
    "frat.ul.o": "frato",
    "fraud.as": "fraŭdas",
    "fraz.o": "",
    "fremis.as (netr)": "tremas~",
    "fren.o": "bremso",
    "frenezi.o": "furiozeco, frenezo",
    "frequ.a": "oftega (pri frekvenco)",
    "fresh.a": "fresha",
    "fricion.as (tr)": "frotas (mekanike aŭ medicine)",
    "fripon.o": "",
    "frit.as": "",
    "frivol.a": "",
    "fromaj.o": "fromaĝo",
    "front.o": "frunto (de kapo); antaŭo",
    "frontier.o": "landlimo",
    "frost.as (netr)": "frostiĝas",
    "frot.as": "",
    "fru.a": "",
    "frukt.o": "",
    "frument.o": "tritiko",
    "fug.as (tr/netr)": "fuĝas",
    "fulgur.as (netr)": "fulmas",
    "fulmin.as": "fulmobatas",
    "fum.as": "",
    "funcion.as (netr)": "funkcias",
    "fund.o": "",
    "fundament.o": "",
    "funel.o": "",
    "funer.o": "funebra solenaĵo",
    "funest.a": "malfavora, pereiga",
    "fung.o": "",
    "fur.o": "pelto",
    "furgon.o": "kamiono fermita flanke kaj supre",
    "furi.as (netr)": "furiozas",
    "furi.oz.a": "furioza",
    "furnaz.o": "forno por fandi metalojn ktp",
    "furnel.o": "kuir- aŭ hejt-forno, stovo",
    "furnis.as (tr)": "liverigas~",
    "furt.as (tr)": "shtelas",
    "fush.as (tr)": "fushas",
    "fusil.o": "",
    "futbal.o": "",
    "futur.o": "estonteco; (gramatiko) futuro",
    "fuz.as (tr)": "fandas",
    "galant.a": "",
    "galeri.o": "",
    "gamb.o": "kruro~",
    "gambit.as (tr)": "stumbligas~",
    "gambol.as (netr)": "saltetadas, petolas~",
    "gan.as (tr)": "gajnas",
    "gans.o": "ansero",
    "gant.o": "",
    "garaj.o": "aŭtejo, remizo, garaĝo",
    "garanti.as": "",
    "gard.as": "",
    "garden.o": "ĝardeno",
    "gas.o": "",
    "gast.o": "",
    "gay.a": "gaja",
    "gazolin.o": "benzino",
    "ge-": "",
    "gem.o": "",
    "gener.al.a": "ĝenerala",
    "gener.o": "genro (en biologio)",
    "generacion.o": "generacio",
    "general.o": "",
    "geni.o": "",
    "geni.oz.o": "geniulo",
    "genit.as (tr)": "generas",
    "genitor.o": "(plurale) gepatroj",
    "genr.o": "genro (en gramatiko)",
    "genu.o": "",
    "geografi.o": "",
    "gest.as": "",
    "gib.o": "tubero~; ĝibo",
    "gichet.o": "giĉeto",
    "glaci.o": "",
    "glas.o": "",
    "glat.a": "",
    "glit.as": "",
    "glob.o": "",
    "glori.o": "gloro",
    "glu.o": "glu(aĵ)o",
    "glut.as": "",
    "glutin.as (tr/netr)": "gluas",
    "golf.o": "golf(lud)o",
    "graci.o": "",
    "grad.o": "shtupo; grado",
    "gram.o": "",
    "gramatik.o": "",
    "gramofon.o": "",
    "gran.o": "grajno",
    "grand.a": "",
    "grandioz.a": "",
    "grant.as (tr)": "donas kiel favoro (ion petatan aŭ deziratan)",
    "gras.o": "",
    "grat.as": "",
    "gratifik.as": "",
    "gratitud.as (tr)": "estas danka al",
    "gratuit.a": "senpaga",
    "gratul.as": "",
    "grav.a": "peza; (pri supersigno) maldekstrakorna; [fig.] grava",
    "gravid.a": "graveda",
    "gret.o": "krado~",
    "gril.as (tr)": "kradrostas",
    "griz.a": "",
    "grond.as (netr)": "muĝas~",
    "gros.a": "ampleksa, dika~",
    "grosier.a": "kruda~, maldelikata~",
    "grotesk.a": "",
    "grozel.o": "groso",
    "gruch.o": "lambastono",
    "grun.as (netr)": "grumblas; gruntas",
    "grup.o": "",
    "gudr.o": "",
    "guid.as (tr)": "gvidas",
    "gulf.o": "golfo (geog.)",
    "gum.o": "",
    "gurt.o": "rimeno (por ligi)",
    "gust.as (tr)": "gustumas",
    "gut.o": "",
    "gutur.o": "gorĝo",
    "guvern.as (tr)": "direktas kun aŭtoritato, regas~",
    "ha!": "",
    "habil.a": "lerta",
    "habit.as": "(konstante) loĝas en",
    "hach.as (tr)": "haĉas",
    "hak.as": "",
    "hal.o": "",
    "halt.as": "",
    "han.o": "kok(in)o",
    "hanch.o": "kokso",
    "handikap.as": "",
    "har.o": "haro (de homa kapo)",
    "hard.a": "malmola",
    "harmoni.as": "",
    "harnes.o": "jungilaro",
    "hast.as (netr)": "rapidas, hastas",
    "haul.as (tr)": "trenas",
    "hav.as": "",
    "hazard.o": "",
    "hef.o": "gisto",
    "heg.o": "heĝo",
    "helic.o": "",
    "helik.o": "",
    "help.as": "",
    "hem.o": "hejmo",
    "herb.o": "",
    "herd.o": "kameno",
    "hered.as": "",
    "hero.o": "",
    "hezit.as": "",
    "hier.e": "hieraŭ",
    "higien.o": "",
    "hik.e": "ĉi tie, tie ĉi",
    "himn.o": "",
    "hip.as (netr)": "singultas",
    "his.as": "",
    "histeri.o": "",
    "histori.o": "",
    "ho.di.e": "hodiaŭ",
    "hobi.o": "",
    "hok.o": "",
    "hola!": "lo!, ha lo!",
    "hom.o": "",
    "honest.a": "",
    "honor.o": "",
    "hor.o": "",
    "horde.o": "",
    "horizont.al.a": "horizontala",
    "horizont.o": "",
    "horloj.o": "horloĝo",
    "horor.as": "",
    "hospital.o": "",
    "host.o": "gastiganto",
    "hotel.o": "",
    "huf.o": "",
    "human.a": "",
    "humid.a": "",
    "humil.a": "",
    "humor.o": "",
    "humur.o": "",
    "hund.o": "",
    "hungr.as (netr)": "estas malsata, malsatas",
    "hura": "",
    "ib.e": "tie",
    "ic.a (= ca)": "ĉi tiu, tiu ĉi (adj.)",
    "ic.o (= co)": "ĉi tio, tio ĉi",
    "ide.al.a": "ideala",
    "ide.o": "",
    "ident.a": "",
    "idiot.o": "",
    "ig.as": "",
    "ignor.as": "",
    "il (= ilu)": "li",
    "ilu": "li",
    "ilu.a": "lia",
    "ilustr.as": "",
    "iluzion.as (netr)": "iluzi-iĝas",
    "imagin.as (tr)": "imagas",
    "imaj.o": "bildo",
    "imens.a": "grandega",
    "imit.as": "",
    "impas.o": "senelirejo",
    "imped.as (tr)": "malhelpas, obstrukcas",
    "imper.as (tr)": "ordonas",
    "impertinent.a": "",
    "implement.o": "mana ilo",
    "implik.as (tr)": "implicas",
    "implor.as (tr)": "emocie petegas (iun)",
    "import.ant.a": "grava",
    "import.as (netr)": "estas grava, gravas",
    "impost.as": "",
    "impoz.as (tr)": "trudas",
    "impregn.as": "",
    "impres.as": "",
    "imprim.as (tr)": "presas",
    "inaugur.as (tr)": "inaŭguras",
    "incit.as (tr)": "antaŭenpushas, instigas, incitas~",
    "index.o": "indekso; montrilo",
    "indic.o": "indikaĵo, signo kiu trovigas ion",
    "indiferent.a": "",
    "indign.as": "",
    "indij.ant.o": "senhavulo",
    "indij.as (tr)": "grave bezonas (kiel malriĉegulo)",
    "indijen.a": "indiĝena",
    "indik.as": "",
    "individu.o": "",
    "indolent.a": "mallaborema, *pigra",
    "industri.o": "",
    "indut.as (tr)": "shmiras",
    "infam.a": "malglora",
    "infant.o": "infano",
    "infekt.as": "",
    "infern.o": "infero",
    "infinit.a": "",
    "infinitiv.o": "",
    "infirm.a": "malforta~, ne povanta uzi normale parton de sia korpo",
    "infl.as (tr)": "shveligas",
    "inflam.as (tr)": "inflamigas",
    "influ.as": "",
    "inform.as": "",
    "infr.e": "malsupre",
    "ingredient.o": "ingredienco",
    "inhib.as (tr)": "inhibicias, inhibas",
    "inici.as (tr)": "inicas; iniciatas",
    "ink.o": "",
    "inklin.as": "klin(iĝ)as, inklinas, emas",
    "inkluz.as (tr)": "inkluzivas",
    "inkur.as (tr)": "altiras sur sin, submetiĝas al",
    "inocent.a": "senkulpa~, kiu ne faras ion malbonan",
    "inquest.as (tr)": "enketas",
    "insekt.o": "",
    "insert.as (tr)": "enmetas, (scienco) insertas",
    "insign.o": "",
    "insist.as": "",
    "insolent.a": "malrespektega",
    "inspekt.as": "",
    "inspir.as": "",
    "instal.as": "",
    "instant.o": "momento",
    "instint.o": "instinkto",
    "instituc.as (tr)": "starigas~",
    "instituc.ur.o": "institucio",
    "institut.o": "",
    "instrukt.as (tr)": "instruas (personon)",
    "instrument.o": "ilo, laborilo",
    "insul.o": "",
    "insult.as": "",
    "integr.a": "",
    "intelekt.as (tr)": "komprenas intelekte",
    "intelekt.o": "",
    "inteligent.a": "",
    "intenc.as": "",
    "intens.a": "",
    "inter": "",
    "inter.nacion.a": "internacia",
    "inter.rupt.as (tr)": "interrompas",
    "interdikt.as (tr)": "malpermesas, (interdiktas~)",
    "interes.as": "",
    "interest.o": "interezo",
    "interim.o": "intertempo",
    "intern.a": "",
    "interpret.as": "",
    "interval.o": "",
    "interviuv.as (tr)": "intervjuas",
    "intim.a": "",
    "intrik.as (tr)": "implikas",
    "introdukt.as (tr)": "prezentas; enkondukas",
    "intruz.as": "entrudiĝas",
    "inund.as": "",
    "invad.as": "",
    "invalid.a": "kiu estas invalido",
    "invalid.o": "",
    "invent.as (tr)": "elpensas, inventas",
    "invers.a": "",
    "invit.as": "",
    "ips.a": "mem",
    "ir.as": "",
    "irac.as (netr)": "estas kolera, koleras",
    "irg.a": "iu ajn (adj.)",
    "irg.a.lok.e": "ie ajn",
    "irg.e.kande": "kiam ajn",
    "irg.o": "io ajn",
    "irg.u": "iu ajn (pron.)",
    "irg.ube": "kie ajn",
    "irit.as (tr)": "incitas~ (D irritieren~, E irritate, F irriter, I irritare, S irritar)",
    "ironi.o": "",
    "it.a (= ta)": "tiu (adj.)",
    "it.o (= to)": "tio",
    "iter.as (tr)": "refojigas, ripetas",
    "izol.as": "",
    "ja": "jam",
    "jac.as (netr)": "kushas~",
    "jaluz.a": "ĵaluza",
    "januar.o": "",
    "jar.o": "vazo el fajenco (por akvo, oleo ktp)",
    "jele.o": "gelatenaĵo, ĵeleo",
    "jem.as (netr)": "ĝemas",
    "jemel.o": "ĝemelo",
    "jen.as (tr)": "ĝenas, malhelpas",
    "jeneroz.a": "malavara, donacema",
    "jentil.a": "ĝentila~",
    "jer.as (tr)": "administras, direktas (firmon por la proprietulo)",
    "jerze.o": "ĵerzo (vesto)",
    "jet.as (tr)": "ĵetas",
    "jinjer.o": "zingibro",
    "jir.as (netr)": "rondiras, ĉirkaŭiras",
    "jok.as": "shercas",
    "joli.a": "beleta~, linda (D hübsĉ, E pretty, F joli, I carino, S bonito, lindo)",
    "jongl.as (netr)": "ĵonglas",
    "jorn.o": "tago~ (periodo de sunlumo)",
    "jovdi.o": "ĵaŭdo",
    "joy.as (netr)": "ĝojas",
    "ju.as (tr)": "ĝuas",
    "judici.as (tr)": "juĝas justice",
    "judik.as": "juĝas (en ĝenerala senco, ne justice)",
    "juli.o": "",
    "jung.as": "",
    "jungl.o": "ĝangalo",
    "juni.o": "",
    "junt.as (tr)": "kunigas",
    "jup.o": "",
    "jur.as": "ĵuras",
    "jurnal.o": "ĵurnalo",
    "jus": "ĵus",
    "just.a": "ĝusta",
    "justifik.as (tr)": "pravigas~ (D reĉtfertigen, E justify, F justifier, I giustificare, S justificar)",
    "juvel.o": "",
    "ka (= kad)": "ĉu",
    "kab.o": "",
    "kaban.o": "",
    "kabl.o": "",
    "kadavr.o": "",
    "kadr.o": "",
    "kaduk.a": "",
    "kafe.o": "kafo",
    "kaj.o": "kaĝo",
    "kalamitat.o": "granda misokazo por multaj personoj, katastrofo~",
    "kaldron.o": "kaldrono~, kuirvazo",
    "kalendari.o": "kalendaro",
    "kalkul.as": "",
    "kalm.a": "kvieta",
    "kalumni.as": "",
    "kalz.et.o": "shtrumpeto",
    "kalz.o": "shtrumpo",
    "kam": "ol, (tiel ..) kiel",
    "kamarad.o": "",
    "kambi.as (tr)": "intershanĝas",
    "kamen.o": "kamentubo",
    "kamer.o": "fotografilo, fotilo",
    "kamion.o": "",
    "kamiz.o": "ĉemizo",
    "kamp.as (netr)": "tendumas, kampas",
    "kampani.as (netr)": "kampanjas",
    "kanal.o": "",
    "kanape.o": "kanapo",
    "kande, kand": "kiam",
    "kandel.o": "",
    "kandid.a": "malkashema",
    "kandidat.o": "",
    "kanel.o": "kanelo; ranuro",
    "kano.o": "kanuo",
    "kanon.o": "",
    "kanot.o": "",
    "kanson.o": "kanzono",
    "kant.as": "",
    "kanvas.o": "",
    "kaos.o": "ĥaoso, kaoso",
    "kap.o": "",
    "kapabl.a": "",
    "kapac.a": "ampleksa~ (pri kapacito)",
    "kapac.es.o": "enhaveco, kapacito",
    "kapel.o": "",
    "kapitan.o": "",
    "kapric.o": "",
    "kapt.as": "",
    "kapuc.o": "kapuĉo",
    "kar.a": "",
    "karakter.o": "",
    "karb.o": "karbono",
    "karbon.o": "karbo",
    "karcer.o": "",
    "kare.as (tr)": "vivas sen bezoni, senigas sin je",
    "karez.as": "karesas",
    "karg.aj.o": "kargo",
    "karg.as (tr)": "sharĝas (varojn en aŭ sur ion)",
    "karier.o": "",
    "karn.o": "(parto de korpo) karno; [por manĝi] viando",
    "karnaval.o": "",
    "karot.o": "",
    "karp.o": "pojno; (fisho) karpo",
    "karpent.as (tr)": "ĉarpentas",
    "kart.o": "karto (ne mapo)",
    "karton.o": "",
    "kas.o": "",
    "kaset.o": "",
    "kasis.o": "ribo",
    "kaskad.o": "",
    "kasquet.o": "kaskedo",
    "kasrol.o": "kaserolo",
    "kastel.o": "",
    "kat.o": "",
    "katalog.o": "",
    "katar.o": "",
    "kataret.o": "malvarmumo",
    "katastrof.o": "",
    "katedral.o": "",
    "kategori.o": "",
    "katen.o": "ĉeno",
    "kauchuk.o": "kaŭĉuko",
    "kaud.o": "vosto",
    "kaul.o": "brasiko",
    "kauz.o": "kaŭzo",
    "kav.a": "",
    "kaval.o": "ĉevalo",
    "kavalk.as": "rajdas",
    "kavern.o": "",
    "kay.o": "kajo",
    "kayer.o": "kajero",
    "kaz.o": "",
    "ke": "",
    "keler.o": "kelo",
    "kelk.a": "iom da, kelka",
    "kern.o": "",
    "kest.o": "",
    "kilogram.o": "",
    "kin": "kvin",
    "kiosk.o": "",
    "kirk.o": "preĝejo, (kirko)",
    "kiropter.o": "vesperto~",
    "kis.as": "",
    "klak.as": "",
    "klam.as (tr)": "ekkrias, kriegas (vortojn)",
    "klar.a": "",
    "klas.o": "",
    "klasik.a": "",
    "klaudik.as (netr)": "lamas",
    "klaun.o": "klaŭno",
    "klav.o": "",
    "klef.apert.as": "malshlosas",
    "klef.kloz.as": "shlosas",
    "klef.o": "shlosilo",
    "klem.as (tr)": "kunpremas",
    "klement.a": "kompatindulga, korfavora",
    "klerik.o": "",
    "klient.o": "",
    "klif.o": "",
    "klikt.as (netr)": "klaktintas, tintegas",
    "klim.as": "grimpas",
    "klimat.o": "",
    "klin.as": "interkovriĝas",
    "klok.o": "horo~, tempo~ horloĝa (ye un kloko = je la unua (horo))",
    "klosh.o": "sonorilo",
    "klov.o": "najlo",
    "kloz.as (tr)": "fermas",
    "klub.o": "",
    "koakt.as (tr)": "devigas perforte",
    "kofr.o": "",
    "koher.as": "",
    "koincid.as": "",
    "kol.o": "",
    "kold.a": "malvarma",
    "koleg.o": "",
    "kolegi.o": "",
    "kolekt.as": "",
    "koli.as (tr)": "deshiras, *plukas",
    "koliar.o": "koliero",
    "kolin.o": "monteto, altaĵo",
    "kolizion.as (netr)": "kolizias",
    "kolm.o": "plej alta rango",
    "kolon.o": "kolono; kojlo",
    "kolor.o": "",
    "kolum.o": "",
    "kolumn.o": "",
    "kom": "kiel~ (estante, en la ofico de)",
    "kom.o": "",
    "kom.o-punt.o": "punktokomo",
    "komand.as": "",
    "kombat.as (tr/netr)": "batalas",
    "kombin.as": "",
    "komedi.o": "",
    "komenc.as (tr/netr)": "komenc(iĝ)as",
    "komend.as (tr)": "mendas",
    "koment.as (tr)": "komentarias, komentas",
    "komerc.as": "",
    "komet.o": "",
    "komfort.o": "",
    "komik.a": "komika~",
    "komitat.o": "",
    "komiz.o": "",
    "komod.a": "konvena, oportuna~",
    "komod.o": "",
    "kompakt.a": "",
    "kompan.o": "kunul(in)o",
    "kompani.o": "",
    "kompar.as": "",
    "kompas.o": "cirkelo",
    "kompat.as": "",
    "kompens.as": "",
    "kompetent.a": "",
    "komplement.o": "",
    "komplet.a": "",
    "komplex.a": "malsimpla, kompleksa",
    "komplez.as (netr)": "komplezas (tr)",
    "komplik.as": "",
    "kompliment.as": "",
    "kompoz.as (tr)": "komponas; konsistigas",
    "kompr.as (tr)": "aĉetas",
    "kompren.as": "",
    "kompres.as (tr)": "malgrandigas per premo, kunpremas~, densigas~",
    "komun.a": "",
    "komunik.as": "",
    "kon.o": "konuso",
    "koncentr.as": "",
    "koncept.as": "",
    "koncern.as": "",
    "koncert.o": "",
    "konci.as (tr)": "konscias",
    "koncienc.o": "konscienco",
    "koncili.as (tr)": "repacigas, akordigas",
    "konciz.a": "",
    "kondamn.as": "",
    "kondens.as": "",
    "kondicion.as (tr)": "kondiĉas",
    "kondol.as (tr)": "kondolencas",
    "konduktor.o": "",
    "kondut.as": "",
    "konekt.as": "",
    "konfer.as (netr)": "konferencas",
    "konfes.as": "",
    "konfid.as": "",
    "konfirm.as": "",
    "konfisk.as": "",
    "konflikt.as": "",
    "konfund.as (tr)": "konfuzas",
    "konfuz.a": "",
    "kongres.as": "",
    "konkav.a": "",
    "konkluz.as (tr)": "konkludas",
    "konkord.as (netr)": "interkonsentas",
    "konkret.a": "",
    "konkurs.as (netr)": "konkuras",
    "konoc.as (tr)": "konas",
    "konquest.as (tr)": "konkeras",
    "konsent.as": "",
    "konsequ.as (netr)": "sekvas (logike)",
    "konserv.as": "",
    "konsider.as": "",
    "konsil.as": "",
    "konsist.as": "",
    "konsolac.as (tr)": "konsolas",
    "konspir.as": "",
    "konsput.as (tr)": "esprimas malestim(ec)on al",
    "konstant.a": "",
    "konstat.as": "",
    "konstern.as": "",
    "konstituc.as (tr)": "konsistigas, formas",
    "konstrikt.as (tr)": "malvastigas, kuntiras",
    "konstrukt.as (tr)": "konstruas",
    "konsult.as": "",
    "konsum.as": "",
    "kont.as (tr)": "nombras",
    "kont.o": "",
    "kontakt.as": "",
    "konten.as (tr)": "enhavas, entenas",
    "kontent.a": "",
    "kontest.as": "",
    "kontinent.o": "",
    "kontinu.a": "",
    "kontor.o": "",
    "kontrast.as": "",
    "kontre": "kontraŭ",
    "kontre.a": "kontraŭa",
    "kontribut.as": "kontribuas",
    "kontrol.as": "",
    "kontur.o": "",
    "kontuz.as": "",
    "konven.as": "",
    "konvers.as (netr)": "konversacias",
    "konvert.as": "",
    "konvex.a": "konveksa",
    "konvink.as": "",
    "kooper.as (netr)": "laboras en kooperativo",
    "koordin.as (tr)": "kunordigas",
    "kopi.as": "",
    "koqu.as (tr)": "kuiras",
    "kor.o": "ĥoro",
    "koram": "en la ĉeesto de, antaŭ~",
    "korb.o": "",
    "kord.o": "shnuro",
    "kordi.o": "koro",
    "kordon.o": "",
    "korekt.a": "",
    "korespond.as": "",
    "koridor.o": "",
    "kork.o": "",
    "korn.o": "",
    "kornik.o": "",
    "korp.o": "",
    "korsaj.o": "korsaĵo",
    "kort.o": "korto (spaco), -ego [de princo], -umo [juĝa]",
    "kost.o": "ripo",
    "kostum.o": "",
    "koton.o": "",
    "kovr.as": "",
    "koz.o": "aĵo",
    "krab.o": "",
    "kran.o": "argano",
    "krani.o": "",
    "kras.o": "malpuraĵo",
    "kravat.o": "",
    "krayon.o": "krajono",
    "kre.as": "",
    "kred.as": "",
    "krem.o": "",
    "kresk.as": "",
    "kresp.o": "",
    "krest.o": "",
    "kret.o": "",
    "krev.as": "",
    "kri.as": "",
    "kribl.o": "kriblilo~",
    "krimin.as (netr)": "krimas",
    "kristal.o": "",
    "kriteri.o": "",
    "kritik.as": "",
    "kriz.o": "",
    "krok.as (tr)": "krakmaĉas",
    "kruc.o": "",
    "kruch.o": "kruĉo",
    "krud.a": "kruda~, en natura stato",
    "kruel.a": "",
    "krug.o": "kruĉo (metala aŭ ligna)",
    "krumpl.as (tr)": "ĉifas",
    "krur.o": "femuro",
    "kub.o": "",
    "kud.o": "kubuto",
    "kuk.o": "",
    "kulier.o": "kulero",
    "kulp.as (netr)": "estas kulpa, kulpas",
    "kulp.o": "",
    "kultel.o": "tranĉilo",
    "kultiv.as": "",
    "kultur.o": "",
    "kun": "",
    "kun.e": "",
    "kun.ven.as": "",
    "kunikl.o": "",
    "kupol.o": "",
    "kupon.o": "",
    "kupr.o": "",
    "kur.as": "",
    "kurac.as": "",
    "kuraj.as (netr)": "kuraĝas",
    "kurier.o": "",
    "kurioz.a": "scivola",
    "kurs.o": "kurso; kurzo",
    "kurt.a": "mallonga",
    "kurten.o": "",
    "kurtez.as (tr)": "amindumas",
    "kurv.a": "kurba",
    "kusen.o": "",
    "kush.as (tr)": "kushigas (kiel por dormi)",
    "kush.as su": "kushas (kiel por dormi)",
    "kust.as (tr)": "kostas",
    "kustum.as (netr)": "kutimas",
    "kustum.o": "kutimo",
    "kuv.o": "",
    "kuvert.o": "koverto",
    "kuz.o": "kuz(in)o",
    "la": "",
    "labi.o": "lipo",
    "labirint.o": "",
    "labor.as": "",
    "lac.o": "laĉo",
    "lacer.as (tr)": "shiras",
    "lag.o": "",
    "lakrim.o": "larmo",
    "lakt.o": "",
    "lam.o": "klingo; lameno",
    "lament.as": "",
    "lamp.o": "",
    "lan.o": "",
    "land.o": "",
    "lang.o": "",
    "lanj.o": "vindotuko",
    "lans.as (tr)": "brandisas~, ĵetas~",
    "lantern.o": "",
    "larj.a": "larĝa",
    "las.as (tr)": "lasas~, permesas~",
    "last.a": "",
    "later.o": "",
    "latrin.o": "necesejo, latrino~",
    "latug.o": "laktuko",
    "laud.as (tr)": "laŭdas",
    "laut.a": "laŭta",
    "lav.as": "",
    "lax.a": "malstreĉita, malfirma",
    "le": "la~ (uzata por indiki pluralon kiam mankas alia indiko)",
    "lecion.o": "",
    "led.a": "malbela",
    "ledr.o": "ledo",
    "leg.o": "leĝo",
    "legend.o": "",
    "legitim.a": "laŭleĝa",
    "legum.o": "legomo",
    "lejer.a": "malpeza",
    "lek.as": "",
    "lekt.as (tr)": "legas",
    "lens.o": "lenso (optiko); lento [bot.]",
    "lent.a": "malrapida, *lanta",
    "lern.as": "",
    "letr.o": "letero",
    "lev.as": "",
    "lever.o": "levilo, levstango, regostango",
    "lez.as (tr)": "lezas; malutilas",
    "li": "ili",
    "li.a": "ilia",
    "liber.a": "",
    "libr.o": "",
    "lid.o": "kovrilo~, fermoplato",
    "lig.as": "",
    "lign.o": "",
    "lik.as": "",
    "limit.o": "limo",
    "limon.o": "citrono",
    "limonad.o": "",
    "line.o": "linio",
    "lineal.o": "liniilo",
    "lingu.o": "lingvo",
    "linj.o": "tolaĵo",
    "liquid.a": "likva",
    "liquid.o": "likvaĵo",
    "list.o": "",
    "lit.o": "",
    "liter.o": "",
    "literatur.o": "",
    "litr.o": "",
    "liv.as (tr)": "forlasas~",
    "livr.as (tr)": "liveras",
    "lo": "ĝi (kiam aludas fakton, ne aĵon)",
    "logik.o": "",
    "loj.as (netr)": "loĝas~",
    "lok.o": "",
    "lokac.as (tr)": "luas",
    "lokomotiv.o": "",
    "lonch.o": "tranĉaĵo",
    "long.a": "",
    "lor": "je la tempo de",
    "lor.e": "tiam",
    "loyal.a": "lojala",
    "lu": "li aŭ shi",
    "lu.a": "lia aŭ shia",
    "lud.as": "",
    "lug.as (tr)": "luigas",
    "lukt.as": "",
    "lum.as": "",
    "lum.o": "",
    "lun.o": "",
    "lundi.o": "lundo",
    "lur.as (tr)": "logas",
    "lux.o": "lukso",
    "ma": "sed",
    "maestr.o": "majstro",
    "magazin.o": "vartenejo, provizejo, staplo",
    "magnet.o": "",
    "magnetofon.o": "",
    "magr.a": "malgrasa, *magra",
    "maiz.o": "",
    "majoritat.o": "plimulto, *majoritato",
    "makul.o": "",
    "mal.a": "malbona",
    "malad.a": "malsana",
    "maledik.as (tr)": "malbenas",
    "maleol.o": "",
    "malgre": "malgraŭ",
    "malic.o": "malic(ec)o; petolado~",
    "malign.a": "malbonintenca; malutila",
    "mam.o": "",
    "manch.o": "tenilo (rekta)",
    "mandat.o": "poshtmandato, monomandato",
    "manet.o": "tenilo turnebla aŭ movebla (ekz. por malfermi pordon)",
    "manier.o": "",
    "manik.o": "",
    "manipul.as": "",
    "manivel.o": "kranko",
    "manj.as (tr)": "manĝas",
    "mank.as": "",
    "manovr.as": "",
    "mantel.o": "",
    "manten.as (tr)": "konservas~, subtenas~",
    "manu.o": "mano",
    "manuskript.o": "",
    "map.o": "mapo, (land)karto",
    "mar.-hund.o": "foko",
    "mar.o": "",
    "march.as (netr)": "marshas",
    "marchand.as (tr)": "marĉandas (ntr)",
    "mardi.o": "mardo",
    "margarin.o": "",
    "mariaj.as (tr)": "geedzigas",
    "mariaj.es.as": "edz(in)iĝas",
    "marionet.o": "",
    "marjin.o": "marĝeno",
    "mark.o": "",
    "marmelad.o": "",
    "marmit.o": "",
    "marmor.o": "",
    "marsh.o": "marĉo",
    "mart.o": "",
    "martel.o": "",
    "martir.o": "",
    "marvel.o": "mirindaĵo",
    "mas.o": "",
    "mashin-skrib.as": "tajpas",
    "mashin.o": "mashino",
    "maskul.a": "virseksa, *maskla",
    "mastik.as (tr)": "maĉas",
    "mastr.o": "",
    "mat.o": "",
    "materi.o": "",
    "matid.a": "malbrila, malhela (pri sono, koloro ktp)",
    "matin.o": "mateno",
    "matr.o": "patrino",
    "matrac.o": "",
    "matur.a": "",
    "maxim": "plej",
    "may.o": "majo",
    "mayuskul.o": "majusklo",
    "me": "mi",
    "me.a": "mia",
    "mech.o": "meĉo",
    "medali.o": "medalo",
    "medi.o": "",
    "medicin.o": "",
    "medik.o": "kuracisto",
    "medikament.o": "",
    "mekanism.o": "",
    "mele.o": "interbatiĝo, miksbatalo",
    "melk.as": "",
    "melodi.o": "",
    "mem": "eĉ",
    "membr.o": "",
    "memor.as": "",
    "mencion.as (tr)": "mencias",
    "mendik.as": "almozas",
    "ment.o": "menso",
    "menti.as (netr)": "mensogas",
    "menton.o": "",
    "menu.o": "",
    "merit.as": "",
    "merk.as (tr)": "notas mense",
    "merkat.o": "vendoplaco; merkato~",
    "merkurdi.o": "merkredo",
    "merl.o": "",
    "mesaj.o": "mesaĝo",
    "meskin.a": "mallarĝanima",
    "mestier.o": "metio",
    "met.as (tr)": "(sur)metas (veston)",
    "metafor.o": "",
    "metal.o": "",
    "metod.o": "",
    "metr.o": "",
    "mez.o": "",
    "mezur.as": "",
    "mi-": "duon-",
    "miel.o": "",
    "mien.o": "",
    "migr.as": "",
    "mikr.a": "malgranda",
    "mil": "",
    "mili.o": "mejlo",
    "milion.o": "",
    "milit.as": "",
    "mim.as": "",
    "min": "malpli",
    "min.as": "",
    "minac.as": "",
    "minim": "malplej",
    "minoritat.o": "malplimulto, *minoritato",
    "minus": "",
    "minuskul.o": "minusklo",
    "minut.o": "",
    "miraj.o": "miraĝo",
    "mirakl.o": "",
    "mis-": "",
    "misteri.o": "mistero",
    "mistik.a": "",
    "mistik.ism.o": "mistiko, -ismo",
    "mit.o": "",
    "mix.as (tr)": "miksas",
    "mizer.as": "",
    "mizer.o": "",
    "mobl.o": "meblo",
    "mod.o": "",
    "model.o": "",
    "moder.as (tr)": "moderigas",
    "modern.a": "",
    "modest.a": "",
    "modifik.as (tr)": "modifas",
    "mok.as": "",
    "mol.a": "",
    "mold.as (netr)": "shimas",
    "molest.as": "",
    "monak.o": "monaĥo",
    "monat.o": "",
    "mond.o": "",
    "monet.o": "monero, mono (metala)",
    "monopol.o": "",
    "monoton.a": "",
    "monstr.o": "",
    "mont.o": "",
    "montr.as": "",
    "monument.o": "",
    "morb.o": "malsano",
    "mord.as": "",
    "morg.e": "morgaŭ",
    "mort.as": "",
    "moskit.o": "",
    "motiv.o": "",
    "motor.o": "",
    "mov.as (tr/netr)": "mov(iĝ)as",
    "moyen.o": "rimedo",
    "muel.as": "",
    "muj.as (netr)": "muĝas~",
    "mulier.o": "virino",
    "mult.a": "multa, multe da",
    "multiplik.as": "",
    "munt.as": "",
    "mur.o": "",
    "murmur.as": "",
    "mus.o": "",
    "mush.o": "musho",
    "muskul.o": "muskolo",
    "must.as (netr)": "devas pro neceso",
    "mut.a": "",
    "muton.o": "shafo",
    "mutual.a": "",
    "muze.o": "",
    "muzik.as": "",
    "nacion.o": "nacio",
    "naiv.a": "",
    "nam": "ĉar~ (D denn, E for, F car, I poiĉé, dato ĉe, S pues)",
    "narac.as (tr)": "rakontas (ion veran)",
    "nask.as (netr)": "naskiĝas",
    "nat.as (netr)": "naĝas",
    "natur.o": "",
    "nav.o": "shipo; navo",
    "naz.o": "",
    "ne": "ne (adv.)",
    "nebul.as (netr)": "estas nebula",
    "nebul.o": "",
    "neces.a": "",
    "neg.as (tr)": "neas, *negas",
    "negativ.a": "",
    "neglij.as (tr)": "neglektas",
    "nek": "",
    "nepot.o": "nepo, -ino",
    "nest.o": "",
    "net.a": "neta, pura",
    "neutr.a": "neŭtra; neŭtrala",
    "nev.o": "",
    "ni": "",
    "ni.a": "",
    "nigr.a": "",
    "nilon.o": "",
    "niv.as (netr)": "neĝas",
    "nivel.o": "",
    "no": "ne (kontraŭaĵo de 'jes')",
    "nobel.a": "",
    "nobl.a": "",
    "noc.as (tr)": "malutilas",
    "noch.o": "noĉo",
    "nod.o": "",
    "nokt.as (netr)": "estas nokto",
    "nokt.o": "",
    "nom.as (tr)": "vokas nomon de, nomas~",
    "nom.o": "",
    "nombr.o": "",
    "non": "naŭ",
    "nord.o": "",
    "norm.al.a": "normala",
    "norm.o": "",
    "not.as": "",
    "nov.a": "",
    "novembr.o": "",
    "nuanc.o": "",
    "nub.o": "",
    "nuc.o": "nukso",
    "nud.a": "",
    "nudl.o": "nudelo",
    "nukle.o": "",
    "nul.a": "neniu (adj.)",
    "nul.o": "nenio",
    "nul.temp.e": "neniam",
    "nul.u": "neniu (pron.)",
    "numer.o": "",
    "nun": "",
    "nun.a": "",
    "nur": "",
    "nur.a": "",
    "nutr.as": "",
    "o": "aŭ",
    "o ... o (= od ... od)": "aŭ ... aŭ",
    "obedi.as (tr)": "obeas",
    "objecion.as (tr)": "kontraŭargumentas",
    "objekt.o": "",
    "oblig.as (tr)": "devigas, komplezas~",
    "obliqu.a": "oblikva",
    "oblivi.as (tr)": "forgesas",
    "oblong.a": "",
    "observ.as": "",
    "obskur.a": "malluma, malklara, *obskura",
    "obsolet.a": "ne plu uzata, arkaika~ (D überholt, veraltet, E obsolete, F dépassé, périmé, I obsoleto, S en desuso)",
    "obstakl.o": "",
    "obstin.as (netr)": "estas obstina, obstinas",
    "obstrukt.as (tr)": "obstrukcas",
    "obten.as (tr)": "havigas~ (D erhalten, E obtain, F obtenir, I ottenere)",
    "ocean.o": "",
    "ocid.as (tr)": "mortigas (perforte)",
    "od (= o)": "aŭ",
    "odi.as (tr)": "malamas",
    "odor.as": "",
    "ofens.as (tr)": "ofendas",
    "ofic.al.a": "oficiala",
    "ofic.o": "",
    "oficir.o": "",
    "ofr.as (tr)": "oferas; ofertas",
    "ofras (tr)": "ofertas (por aĉeto / kompro)",
    "oft.a": "",
    "oft.e": "",
    "ok": "",
    "okazion.o": "kazo~, okazo~, tempo oportuna",
    "oktobr.o": "",
    "okul.o": "",
    "okup.as": "",
    "ol (= olu)": "ĝi",
    "old.a": "maljuna, *olda",
    "ole.o": "",
    "oli": "ili (tiuj aĵoj)",
    "olim": "iufoje, antaŭe",
    "oliv.o": "",
    "olu": "ĝi",
    "olu.a": "ĝia",
    "ombr.o": "",
    "omis.as (tr)": "preterlasas",
    "omlet.o": "",
    "omn.a": "ĉiŭ (adj.) [D jeder, alle, E every, I ogni, S todo]",
    "omn.i": "ĉiuj (pron.)",
    "omn.o": "ĉio",
    "omn.u": "ĉiu (pron.)",
    "omnibus.o": "aŭtobuso",
    "on (= onu)": "oni",
    "ond.o": "",
    "onkl.in.o": "",
    "onkl.o": "onklo aŭ onklino",
    "onkl.ul.o": "onklo",
    "onu": "oni",
    "onu.a": "onia",
    "onyon.o": "cepo",
    "opak.a": "maldiafana",
    "opinion.as (netr)": "opinias",
    "oportun.a": "",
    "opoz.as (tr)": "kontraŭ(star)as, *oponas",
    "opres.as (tr)": "premas~",
    "optim.ism.o": "",
    "optim.ist.o": "",
    "or.o": "",
    "oranj.o": "oranĝo",
    "ordin.as (tr)": "ordigas",
    "ordinar.a": "",
    "orel.o": "",
    "orfan.o": "orfo",
    "organ.iz.as (tr)": "organizas",
    "organ.o": "",
    "origin.al.a": "originala",
    "origin.o": "",
    "orn.as (tr)": "ornamas",
    "ornament.o": "ornamaĵo",
    "ort.a": "",
    "ortodox.a": "ortodoksa",
    "ost.o": "",
    "ov.o": "",
    "oval.a": "",
    "pac.as (netr)": "estas je paco",
    "pac.o": "",
    "pacient.a": "pacienca",
    "paf.as": "",
    "pag.as": "",
    "pagin.o": "paĝo",
    "pak.o": "",
    "pal.a": "",
    "palac.o": "",
    "pali.o": "pajlo",
    "palis.o": "",
    "palm.o": "manplato, *polmo; palmobranĉo",
    "palp.as (tr)": "palpas~",
    "paltot.o": "palto",
    "pan.o": "",
    "pane.as": "",
    "panel.o": "",
    "panoram.o": "",
    "pantalon.o": "",
    "pantofl.o": "",
    "paper.o": "",
    "papilion.o": "papilio",
    "par-": "el- (komplete; ekz. parlernas)",
    "par.a": "",
    "par.o": "",
    "para-": "protektilo (ekz. parapluvo)",
    "para.pluv.o": "(pluv)ombrelo",
    "paradiz.o": "",
    "paradox.o": "paradokso",
    "paragraf.o": "",
    "paralel.a": "",
    "pardon.as": "",
    "parent.a": "parenca",
    "parfum.o": "",
    "pari.as (tr)": "vetas",
    "park.o": "",
    "parok.o": "pastro paroĥa",
    "parol.as": "",
    "part.o": "",
    "partener.o": "kundancant(in)o, kunludant(in)o",
    "parti.o": "grupo (por amuzo, ludo, ĉaso)",
    "partikular.a": "aparta~, speciala~",
    "partis.o": "partio",
    "partur.as (tr)": "akushas",
    "pas.as": "",
    "pasabl.a": "ĵus akceptebla, sufiĉa, sufiĉe bona",
    "pasion.o": "pasio",
    "pasiv.a": "",
    "pasport.o": "",
    "past.o": "",
    "pastel.o": "pashtelo",
    "pastet.o": "pasteĉo~",
    "pastor.o": "",
    "patetik.a": "kortusha, korshira",
    "patr.o": "",
    "patriot.a": "",
    "pauz.as (netr)": "paŭzas",
    "pav.o": "pavimero",
    "pavon.o": "pavo",
    "pavor.as (netr)": "timas (instinkte)",
    "paz.as (netr)": "pashas",
    "pec.o": "",
    "ped.o": "piedo",
    "peizaj.o": "pejzaĝo",
    "pek.as": "",
    "pekt.as (tr)": "kombas",
    "pektor.o": "brusto",
    "pekuni.o": "mono",
    "pel.o": "haŭto",
    "pen.as": "",
    "pend.as (tr/netr)": "pend(ig)as",
    "pens.as": "",
    "per": "",
    "perd.as": "",
    "perfekt.a": "",
    "perfid.a": "",
    "period.o": "",
    "peris.as (netr)": "pereas",
    "perman.ant.a": "konstanta~, daŭra senĉese",
    "perman.as (netr)": "daŭras senĉese",
    "permis.as (tr)": "permesas",
    "person.o": "",
    "persuad.as (tr)": "persvadas",
    "pesk.as": "fishas, fishkaptas",
    "petr.o": "shtono (materio)",
    "petul.as (netr)": "petolas~",
    "pez.as": "",
    "pikt.as (tr)": "pentras",
    "pikt.ur.o": "pentraĵo",
    "pil.o": "haro~ (alia ol de homa kapo)",
    "pinch.as (tr)": "pinĉas",
    "pingl.o": "",
    "pint.o": "",
    "pip.o": "",
    "piz.o": "",
    "plac.o": "",
    "plad.o": "",
    "plafon.o": "",
    "plaj.o": "plaĝo",
    "plak.o": "plato",
    "plan.a": "ebena",
    "pland.o": "",
    "plank.o": "tabulo",
    "plant.o": "",
    "plantac.as (tr)": "plantas",
    "plas.o": "loko~ (por persono aŭ aĵo)",
    "plat.a": "",
    "ple.as (tr)": "ludas~ (rolon, instrumenton ktp)",
    "plen.a": "",
    "plend.as": "",
    "plez.as": "plaĉas",
    "plezur.o": "",
    "plor.as": "",
    "plu": "pli",
    "plug.as": "",
    "plum.o": "",
    "plunj.as (netr)": "plonĝas",
    "plur.a": "",
    "plur.al.o": "",
    "plus": "",
    "plus.a": "kroma, aldona, ekstra",
    "pluv.as": "",
    "po": "",
    "pok.a": "malmulta",
    "polex.o": "polekso",
    "polic.o": "",
    "polis.as (tr)": "poluras",
    "polit.a": "ĝentila~ (D höfliĉ, E polite, F poli, I cortese, S cortés, correcto)",
    "polv.o": "",
    "pom.o": "",
    "ponder.as (tr)": "pesas",
    "pont.o": "",
    "popul.o": "popolo",
    "popular.a": "",
    "por": "",
    "por ke": "",
    "porcion.o": "porcio",
    "pord.o": "",
    "port.as": "",
    "portu.o": "haveno",
    "pos": "post",
    "pos.-di.mez.o": "posttagmezo",
    "posed.as": "",
    "posh.o": "posho",
    "posibl.a": "ebla",
    "post.o": "poshto",
    "postul.as": "",
    "pov.as": "",
    "pov.o": "",
    "povr.a": "malriĉa, *povra",
    "poz.as (tr)": "metas",
    "praktik.as": "",
    "prec.o": "prezo",
    "precipu.a": "ĉefa, precipa",
    "preciz.a": "preciza (klare determinita)",
    "prefer.as": "",
    "pregas (religie) (tr)": "preĝas~",
    "pregas (tr)": "petas (iun, pri/por io)",
    "pren.as": "",
    "prepar.as": "",
    "pres.as (tr)": "premas",
    "preske": "preskaŭ",
    "prest.as (tr)": "pruntas~, pruntedonas",
    "preter": "",
    "prevent.as (tr)": "malebligas, *preventas",
    "prezent.a": "ĉeestanta; nuntempa; (gramatiko) prezenca",
    "prezerv.as (tr)": "prezervas, protektas~, savas~, shirmas~ (de vundo aŭ malutilo)",
    "pri": "",
    "princip.o": "",
    "printemp.o": "",
    "privat.a": "",
    "priz.as (tr)": "shatas",
    "prizent.as (tr)": "prezentas",
    "pro": "",
    "pro ke": "ĉar~ (D da, weil, E because, F parce que, I perĉé, S porque)",
    "pro quo": "kial",
    "prob.as (tr)": "provas",
    "probabl.a": "vershajna, probabla",
    "problem.o": "",
    "produkt.as": "",
    "profesion.o": "profesio",
    "profit.as": "",
    "profund.a": "",
    "projet.as (tr)": "projektas",
    "proklam.as": "",
    "prokur.as (tr)": "havigas~ (D versĉaffen, E procure, F procurer, I procurare)",
    "promen.as": "",
    "promis.as (tr)": "promesas",
    "pront.a": "preta",
    "proporcion.o": "proporcio",
    "propoz.as (tr)": "proponas",
    "propr.a": "",
    "propriet.as": "",
    "protekt.as": "",
    "proverb.o": "",
    "proviz.as": "",
    "provizor.a": "",
    "proxim": "proksima al, apud~",
    "prudent.a": "",
    "prunt.as (tr)": "pruntas~, prunteprenas",
    "pruv.as": "",
    "publik.a": "",
    "puer.in.o": "knabino",
    "puer.o": "knabo aŭ knabino",
    "puer.ul.o": "knabo",
    "puls.as (tr)": "pushas",
    "pulver.o": "pulvoro",
    "punis.as (tr)": "punas",
    "punt.o": "punkto",
    "pur.a": "",
    "qua": "kiu",
    "quadrat.a": "kvadrata",
    "qual.a": "kia",
    "qual.e": "kiel",
    "qual.es.o": "kvalito",
    "quankam": "kvankam",
    "quant.a": "kiom da, kioma",
    "quant.o": "kvanto",
    "quar.im.o": "kvarono",
    "quas": "kvar",
    "quaz.e": "kvazaŭ",
    "quer.as (tr)": "iras por alporti, venigas~ (D (ab)holen, E fetĉ, F quérir, S ir en busca de, buscar)",
    "question.as": "demandas",
    "qui": "kiuj",
    "quiet.a": "trankvila (mense)",
    "quik": "tuj",
    "quo": "kio",
    "racion.o": "racio",
    "radi.as": "",
    "radi.o": "",
    "radik.o": "",
    "raft.o": "floso",
    "rag.o": "ĉifono",
    "rajunt.as (tr)": "atingas~, ĝisiĝas",
    "raket.o": "rakedo, (raketo)",
    "rakont.as (tr)": "rakontas (ion fikcian)",
    "ram.o": "branĉeto, vergo~",
    "ramp.o": "deklivo (supren)",
    "ran.o": "",
    "rang.o": "rango; serio~, etendiĝo~",
    "rapid.a": "",
    "raport.as": "",
    "rar.a": "",
    "ras.o": "",
    "rat.o": "",
    "rauk.a": "raŭka",
    "raz.as": "",
    "reakt.as (netr)": "reagas, reakcias",
    "real.a": "",
    "recent.a": "antaŭnelonga, lastatempa",
    "recept.o": "",
    "recev.as (tr)": "ricevas",
    "reciprok.a": "",
    "red.a": "ruĝa",
    "redakt.as": "",
    "redukt.as": "",
    "refer.as": "direktas~, rilatigas~",
    "reflekt.as": "",
    "refut.as": "",
    "refuz.as (tr)": "rifuzas",
    "regard.as (tr)": "rigardas",
    "region.o": "",
    "registr.o": "",
    "regn.as": "regas",
    "regret.as (tr)": "bedaŭras",
    "regul.as (tr)": "regul(ig)as",
    "regul.o": "",
    "rej.o": "reĝ(in)o",
    "rejim.o": "reĝimo",
    "reklam.as": "",
    "rekolt.as (tr)": "rikoltas",
    "rekomend.as": "",
    "rekompens.as (tr)": "rekompencas",
    "rekord.o": "",
    "rekt.a": "",
    "rel.o": "",
    "relat.as": "rilatas (ntr)",
    "religi.o": "",
    "rem.as": "",
    "remark.as (tr)": "rimarkas",
    "remedi.as (tr)": "resanigas~ (malsan(ec)on)",
    "remplas.as (tr)": "anstataŭas",
    "renkontr.as (tr)": "renkontas",
    "renvers.as": "",
    "repar.as (tr)": "riparas",
    "repast.as (netr)": "manĝas~ (je regula okazo)",
    "repast.o": "manĝo~ (D Essen, Mahlzeit, E meal, F repas, I pasto)",
    "repent.as": "pentas",
    "repet.as (tr)": "ripetas",
    "repoz.as (netr)": "ripozas",
    "repres.as (tr)": "(sub)premas; repushas~",
    "reprezent.as": "",
    "reprimand.as (tr)": "admonas~",
    "reproch.as (tr)": "riproĉas",
    "rept.as (netr)": "rampas",
    "republik.o": "respubliko",
    "repugn.as (tr)": "produktas grandan antipation en",
    "repuls.as (tr)": "repushas, forpushas, forpelas",
    "respekt.as": "",
    "respir.as (tr/netr)": "spiras",
    "respond.as": "",
    "respons.as (netr)": "respondecas, prirespondas, (responsas)",
    "rest.as": "",
    "restaur.as (tr)": "*restaŭras",
    "restor.as (tr)": "donas manĝaĵon kaj trinkaĵon por konsumo",
    "restor.eri.o": "restoracio",
    "restrikt.as (tr)": "limigas",
    "ret.o": "",
    "reten.as (tr)": "(re)tenas",
    "retro": "malantaŭen",
    "retro-": "re-, retro-",
    "rev.as": "",
    "revel.as (tr)": "malkashas; rivelas",
    "revenu.o": "enspezo",
    "reviz.as (tr)": "revizias~, (revizas~)",
    "revu.as": "",
    "revu.o": "",
    "rez.a": "samnivela",
    "rezerv.as": "",
    "rezid.as": "",
    "rezidu.o": "restaĵo; rekremento",
    "rezign.as": "rezignacias",
    "rezist.as": "",
    "rezolv.as (tr)": "decidas~ (pri ago) [D besĉliessen, E resolve (to), F résoudre (de faire)]",
    "rezon.as": "",
    "rezult.as": "",
    "rezum.as (tr)": "resumas",
    "ri-": "re-",
    "ri.konoc.as (tr)": "rekonas",
    "ri.san.ig.as": "resanigas (malsanulon)",
    "rich.a": "riĉa",
    "rid.as": "",
    "rid.et.as": "",
    "rigid.a": "",
    "rim.o": "",
    "rimen.o": "",
    "rinforc.as (tr)": "plifortigas",
    "ring.o": "",
    "rins.as (tr)": "tralavas~, lavetas~ (E rinse, F rincer)",
    "rip.as": "flankenglitas, joras~",
    "risk.as": "",
    "ritm.o": "",
    "riv.o": "bordo",
    "rival.a": "",
    "river.o": "",
    "riz.o": "",
    "rob.o": "",
    "robinet.o": "krano",
    "rok.o": "",
    "rol.o": "",
    "roman.o": "",
    "romantik.a": "romantika",
    "rond.a": "",
    "rost.as": "",
    "rot.o": "rado",
    "roz.o": "",
    "ruband.o": "",
    "rubarb.o": "rabarbo",
    "rud.a": "kruda~, maldelikata, triviala~",
    "ruin.as (tr)": "ruinigas",
    "rul.as (tr/netr)": "rul(iĝ)as",
    "rupt.as (tr)": "rompas",
    "rur.o": "kamparo",
    "rust.o": "",
    "rutin.o": "",
    "sabl.o": "",
    "saj.a": "saĝa",
    "sak.o": "",
    "sakr.a": "sankta (respekteginda)",
    "sal.o": "",
    "salad.o": "salato",
    "salari.as (tr)": "donas salajron al",
    "salari.o": "salajro",
    "salon.o": "",
    "salt.as": "",
    "salut.as": "",
    "salv.as (tr)": "savas",
    "sam.a": "",
    "san.a": "",
    "sandal.o": "",
    "sang.o": "",
    "sant.a": "sankta (religie purega)",
    "sapon.o": "sapo",
    "sapor.as (netr)": "gust-umas",
    "sark.o": "ĉerko",
    "sarkl.as (tr)": "sarkas",
    "sat": "sufiĉe, adekvate",
    "satisfac.as (tr)": "kontentigas, plenumas",
    "saturdi.o": "sabato",
    "sauc.o": "saŭco",
    "sav.as (tr)": "scias",
    "se": "",
    "sed.o": "postaĵo (de korpo)",
    "sediment.o": "",
    "sedukt.as (tr)": "delogas",
    "seg.as": "",
    "segl.o": "velo",
    "segment.o": "",
    "segun": "laŭ",
    "sek.as (tr)": "tranĉetas~, sekcas~, dividas tranĉete",
    "sekret.a": "",
    "sekund.o": "",
    "sekur.a": "",
    "selekt.as (tr)": "elektas~, (selektas), prenas prefere",
    "sem.as": "",
    "seman.o": "semajno",
    "sembl.as (netr)": "shajnas",
    "semin.o": "semo",
    "sempre": "ĉiam",
    "sen": "",
    "sen-": "",
    "senc.o": "",
    "send.as": "",
    "sens.o": "",
    "sent.as": "",
    "sentiment.o": "",
    "sep": "",
    "separ.as (tr)": "apartigas, disigas, (separas)",
    "septembr.o": "",
    "sequ.as (tr)": "sekvas",
    "serch.as (tr)": "serĉas",
    "seri.o": "",
    "serioz.a": "",
    "serpent.o": "",
    "serur.o": "",
    "serv.as": "",
    "sever.a": "",
    "sezon.o": "",
    "sfer.o": "",
    "sham.as (netr)": "hontas",
    "shancel.as (netr)": "shanceliĝas",
    "sharp.o": "skarpo",
    "shirm.as (tr)": "shirmas",
    "shok.as (tr)": "shokas~, trafas~, batas~",
    "shu.o": "shuo",
    "shultr.o": "shultro",
    "sid.as": "",
    "sifl.as (tr/netr)": "fajfas",
    "sign.o": "",
    "signal.as": "",
    "signat.as (tr)": "subskribas",
    "signifik.as (tr)": "signifas",
    "sik.a": "seka",
    "sikl.o": "falĉileto, serpo",
    "silenc.as (netr)": "silentas (ne faras bruon)",
    "silenc.o": "silento (manko de bruo)",
    "silk.o": "",
    "simbol.o": "",
    "simil.a": "",
    "simpati.as (tr)": "havas simpation por",
    "simpl.a": "",
    "simptom.o": "",
    "sincer.a": "",
    "singl.a": "ĉiŭ (D jeder einzelne, E eaĉ, I ciascuno, S cada)",
    "singl.u": "ĉiŭ (pron.)",
    "singlut.as (netr)": "spasmoploras, plorsingultas",
    "singular.a": "",
    "sinior.o": "moshto~, sinjoro~",
    "sinistr.a": "maldekstra",
    "sink.as (tr/netr)": "malleviĝas, -igas, sink(ig)as",
    "sins.o": "direkto~, senco~ (A al B aŭ B al A sed ne ambaŭ)",
    "sior.in.o": "sinjorino",
    "sior.o": "sinjoro, (-ino)",
    "sior.ul.o": "sinjoro",
    "sirop.o": "",
    "sis": "ses",
    "sis.as (netr)": "siblas",
    "sistem.o": "",
    "sitel.o": "",
    "situ.as (tr)": "lokas, situigas",
    "situ.es.o": "situacio, situo",
    "siv.o": "kriblilo (fajna)",
    "sive ... sive": "ĉŭ .. ĉŭ",
    "siz.as (tr)": "(ek)kaptas~ (D ergreifen, E seize, F saisir, I afferrare, S agarrar)",
    "skal.o": "shtupetaro, *eskalo; skalo",
    "skars.a": "malabunda",
    "skem.o": "",
    "skeptik.a": "",
    "skeptik.o": "skeptikulo",
    "skis.as (tr)": "skizas",
    "skol.o": "lernejo; skolo~",
    "skop.o": "celo",
    "skrap.as": "",
    "skren.o": "ekrano",
    "skrib.as": "",
    "skrub.in.o": "shraŭbingo, boltingo",
    "skrub.o": "shraŭbo",
    "soci.al.a": "sociala, socia",
    "soci.et.o": "",
    "soci.o": "",
    "socis.o": "kolbaso",
    "sol.a": "",
    "soldat.o": "",
    "solen.a": "",
    "solid.a": "",
    "solitar.a": "sola~, izola~ (D einsam, abgelegen, E solitary, F solitaire, IS solitario)",
    "solv.as": "",
    "somer.o": "",
    "somit.o": "supro~, (supra) pinto",
    "son.as": "",
    "sonj.as (netr)": "sonĝas",
    "sonor.a": "",
    "sordid.a": "malpura, *sordida",
    "sorg.as (tr)": "zorgas~",
    "sort.o": "speco",
    "sospir.as (netr)": "suspiras",
    "sovaj.a": "sovaĝa",
    "spac.o": "",
    "spad.o": "fosilo, shpato",
    "spar.as (tr/netr)": "shparas",
    "spec.o": "specio",
    "specimen.o": "",
    "spegul.o": "",
    "spekt.as": "",
    "spektakl.o": "",
    "spens.as (tr)": "elspezas",
    "spic.o": "",
    "spin.o": "",
    "spiral.o": "",
    "spirit.o": "",
    "splendid.a": "belega~, grandioza~, brila~ (D glänzend, E splendid, F splendide, I splendido, S espléndido)",
    "spoli.as (tr)": "rabas",
    "sponj.o": "spongo",
    "spontan.a": "",
    "sport.o": "",
    "spoz.in.o": "edzino",
    "spoz.o": "edz(in)o",
    "spoz.ul.o": "edzo",
    "spum.o": "shaŭmo",
    "sput.as (tr)": "kraĉas; (malsane) sputas",
    "squat.as (netr)": "kaŭras~, sidas sur siaj kalkanoj",
    "stabil.a": "",
    "stabl.o": "stalo",
    "stac.as (netr)": "staras",
    "stacion.o": "stacio",
    "stadi.o": "stadio~ = loko por konkursoj atletaj ktp",
    "stagn.as": "",
    "stal.o": "shtalo",
    "stand.as (netr)": "fartas",
    "stand.o": "stato",
    "standard.o": "",
    "stang.o": "",
    "start.as (tr/netr)": "ekfunkci(ig)as, start(ig)as",
    "stat.o": "shtato",
    "stel.o": "",
    "steril.a": "",
    "stil.o": "",
    "stipul.as (tr)": "kondiĉas",
    "stof.o": "shtofo",
    "stok.o": "",
    "stomak.o": "",
    "ston.o": "shtono (individua, ne la materio)",
    "stop.as (tr)": "shtopas",
    "strad.o": "strato",
    "stranj.a": "stranga",
    "stranjer.a": "fremda",
    "strat.o": "tavolo; *stratumo",
    "strategi.o": "",
    "strek.o": "",
    "stret.a": "mallarĝa",
    "stri.o": "tre streta kanelo",
    "strik.as": "",
    "strikt.a": "",
    "struktur.o": "",
    "student.o": "",
    "studi.as (tr/netr)": "studas",
    "stul.o": "seĝo",
    "stult.a": "malsaĝa",
    "stupid.a": "stult(eg)a",
    "sturm.as (netr)": "estas shtorma",
    "sturm.o": "shtormo",
    "su": "si",
    "su.a": "sia",
    "sub": "",
    "subis.as (tr)": "ricevas aŭ suferas devigite",
    "subit.a": "",
    "subjekt.o": "",
    "substanc.o": "",
    "substantiv.o": "",
    "substituc.as (tr)": "substituas",
    "subterfuj.o": "artifiko~",
    "subtil.a": "",
    "suced.as (tr)": "sekvas sen interrompo",
    "suces.as (netr)": "sukcesas",
    "suci.as (tr)": "zorgas~ pri, maltrankvilas~ pri",
    "sud.o": "",
    "sudor.o": "shvito",
    "sufic.as (netr)": "sufiĉas",
    "sufl.as (tr/netr)": "blovas",
    "sufok.as": "",
    "sufr.as (netr)": "suferas",
    "sug.as (tr)": "suĉas",
    "sugest.as": "",
    "suk.o": "",
    "sukomb.as (netr)": "subfalas",
    "sukr.o": "sukero",
    "sukus.as (tr)": "skuas",
    "sul.o": "grundo",
    "sum.o": "",
    "sun.o": "",
    "sundi.o": "dimanĉo",
    "suol.o": "plandumo",
    "sup.o": "",
    "supe.as (netr)": "manĝas manĝaĵon ĉirkaŭ noktomezo",
    "super": "",
    "superflu.a": "super-flua",
    "superior.a": "aŭtoritate supera",
    "superstic.o": "superstiĉo",
    "suple.as (tr)": "anstataŭas provizore",
    "suplement.o": "",
    "suplik.as (tr)": "petegas humile (iun pri io)",
    "suport.as (tr)": "subtenas~",
    "supoz.as": "",
    "supr.a": "",
    "supr.e": "",
    "supres.as (tr)": "subpremas, malebligas ekziston de",
    "sur": "",
    "surd.a": "",
    "surfac.o": "supraĵo, surfaco",
    "surpriz.as": "",
    "surtut.o": "varma palto",
    "suspekt.as": "",
    "suspend.as (tr)": "pendigas",
    "susten.as (tr)": "subtenas~, helpas subteni",
    "sustracion.as (tr)": "subtrahas",
    "susur.as": "flustras",
    "sut.as (tr)": "kudras",
    "suvenir.o": "memoraĵo",
    "swich.as (tr)": "shaltas",
    "ta (= ita)": "tiu (adj.)",
    "tabel.o": "",
    "tabl.o": "",
    "tabul.o": "breto",
    "tac.as (tr/netr)": "diras nenion, silentas~",
    "tal.a": "tia",
    "tal.e": "tiel",
    "talent.o": "",
    "talior.o": "tajloro",
    "talisman.o": "",
    "tam ... kam": "tiel ... kiel",
    "tamen": "",
    "tandem": "finfine (post longa atendo)",
    "tank.o": "tanko; fermita metala rezervujo",
    "tant.a": "tiom da, tioma, tiel multa",
    "tant.e": "tiel (multe)",
    "tapis.o": "tapisho",
    "tard.a": "malfrua",
    "tart.o": "torto",
    "tas.o": "",
    "task.o": "",
    "tast.as (netr)": "palpas~, palpserĉas",
    "tavern.o": "",
    "tay.o": "talio",
    "te.o": "",
    "teatr.o": "",
    "ted.as": "",
    "teg.as": "",
    "teknik.o": "",
    "tekt.o": "tegmento",
    "telefon.as (tr)": "telefonas",
    "tem.o": "",
    "temp.o": "",
    "temperament.o": "",
    "temperatur.o": "",
    "tempest.as (netr)": "estas tempesto",
    "ten.as": "",
    "tenac.a": "",
    "tendenc.as": "",
    "tenebr.o": "mallumo, (tenebro)",
    "tener.a": "molkora, *tenera",
    "tens.as (tr)": "streĉas",
    "tent.as": "",
    "tenu.a": "fajna~, maldika kaj longa",
    "tepid.a": "varmeta, *tepida",
    "ter.o": "",
    "ter.pom.o": "",
    "teror.as (netr)": "teruriĝas",
    "text.o": "teksto",
    "ti (= iti)": "tiuj (pron.)",
    "til": "ĝis",
    "tim.as (tr)": "timas (intelekte, racie)",
    "timid.a": "malaŭdaca, (timida)",
    "tip.o": "",
    "tir.as": "",
    "titil.as (tr)": "tiklas",
    "titul.o": "titolo",
    "to (= ito)": "tio",
    "toal.o": "tualeta tuko, mantuko~, bantuko~",
    "toler.as": "",
    "tomat.o": "",
    "tomb.o": "",
    "ton.o": "",
    "tond.as": "",
    "tondr.as": "",
    "torch.o": "torĉo",
    "tord.as": "",
    "torent.o": "",
    "tors.o": "",
    "tort.o": "pasteĉo~ (ronda)",
    "tot.a": "tuta",
    "tra": "",
    "traduk.as": "",
    "trafik.o": "",
    "tragedi.o": "",
    "trahiz.as (tr)": "perfidas",
    "trakt.as": "",
    "tranch.as (tr)": "tranĉas (tute tra)",
    "tranquil.a": "trankvila",
    "trans": "",
    "transfer.as (tr)": "transigas, transdonas",
    "translucid.a": "diafana",
    "transport.as": "",
    "transvers.a": "",
    "tras.as (tr)": "desegnas skize",
    "traur.as (netr)": "funebras",
    "tre": "",
    "trek.o": "vojstreko",
    "trelis.o": "latiso",
    "trem.as": "",
    "tren.o": "trajno",
    "trest.o": "stablo",
    "trezor.o": "",
    "tri": "",
    "trikot.as (tr)": "trikas",
    "trist.a": "malgaja, malĝoja, (trista)",
    "tro": "",
    "trog.o": "",
    "tromp.as": "",
    "trotuar.o": "",
    "trov.as": "",
    "tru.o": "",
    "trubl.as (tr)": "maltrankviligas",
    "trunk.o": "",
    "trup.o": "",
    "tu": "ci",
    "tu.a": "cia",
    "tualet.-tuk.o": "mantuko; bantuko",
    "tualet.as (netr)": "faras tualeton (lavon ktp)",
    "tualet.o": "",
    "tub.o": "",
    "tuf.o": "",
    "tuk.o": "",
    "tunel.o": "",
    "tur.ist.o": "turisto",
    "tur.o": "rondvojaĝo",
    "turb.o": "amaso (de personoj)",
    "turm.o": "turo",
    "turn.as (tr/netr)": "turn(iĝ)as",
    "tus.as": "",
    "tush.as (tr)": "tushas",
    "ube": "kie",
    "ucel.o": "birdo",
    "ul.a": "iu (adj.)",
    "ul.o": "io",
    "ul.u": "iu (pron.)",
    "ultr.a": "kroma, plua",
    "ultr.e": "krom",
    "un": "unu",
    "un.esm.a": "unua",
    "un.foy.e": "unufoje",
    "unanim.a": "unuanima",
    "ungl.o": "ungo",
    "unguent.o": "shmiraĵo, ungvento",
    "uniform.a": "unuforma, samaspekta",
    "uniform.o": "",
    "unik.a": "",
    "union.as (tr)": "unuigas",
    "union.o": "unuiĝo, unio",
    "uragan.o": "",
    "urb.o": "",
    "urj.as (netr)": "urĝas~",
    "urs.o": "",
    "utensil.o": "(praktika) ilo, ujo",
    "util.a": "",
    "uz.as": "",
    "vagon.o": "",
    "vak.as": "",
    "vakanc.as (netr)": "ferias",
    "vaku.a": "malplena",
    "val.o": "",
    "valid.a": "",
    "valiz.o": "",
    "valor.as": "",
    "van.a": "",
    "vang.o": "",
    "vanitat.o": "vantemo~ (D Eitelkeit, E vanity, F vanité, I vanità, S vanidad)",
    "vapor.o": "",
    "var.o": "",
    "vari.as": "",
    "varm.a": "",
    "vars.as (tr)": "vershas",
    "vart.as (tr)": "atendas~ (ĝis okazo)",
    "vast.a": "",
    "vax.o": "vakso",
    "vaz.o": "",
    "veh.as (netr)": "veturas (en veturilo)",
    "vein.o": "vejno",
    "vek.as (netr)": "vekiĝas",
    "vek.ig.as (tr)": "vekas",
    "ven.as": "",
    "vend.as": "",
    "venen.o": "",
    "venerdi.o": "vendredo",
    "vent.as (netr)": "blovas~",
    "vent.o": "",
    "ventr.o": "",
    "ver.a": "",
    "verb.o": "",
    "verd.a": "",
    "verg.o": "",
    "vers": "al~, en direkto al (D ige(ge)n, auf ... zu, naĉ ... zu, -wärts, E toward(s), F vers, S hacia, I verso)",
    "version.o": "versio",
    "vertikal.a": "",
    "vertu.o": "virto",
    "verv.o": "",
    "vesp.o": "",
    "vesper.o": "",
    "vest.o": "",
    "veston.o": "jako (vira)",
    "veter.o": "",
    "vetur.o": "veturilo",
    "vex.as (tr)": "ĉagrenas",
    "vi": "vi (plurala)",
    "vi.a": "via (plurale)",
    "vibr.as": "",
    "vice": "anstataŭ",
    "vici.o": "malvirto",
    "vicin.a": "najbara",
    "vid.as": "",
    "vidv.a": "",
    "vigor.o": "fortikeco (korpa, spirita)",
    "viktim.o": "",
    "vilaj.o": "vilaĝo",
    "vin.o": "",
    "vinagr.o": "",
    "vink.as (tr)": "venkas",
    "vintr.o": "",
    "violent.as (tr)": "perfortas (iun)",
    "violent.o": "perforto~",
    "vir.o": "",
    "vis.as (tr/netr)": "shraŭbas",
    "vish.as (tr)": "vishas",
    "vitr.o": "",
    "viv.as": "",
    "vivac.a": "viveca, verva",
    "viz.as (tr/netr)": "celas",
    "vizaj.o": "vizaĝo",
    "vizit.as": "",
    "voc.o": "voĉo",
    "vok.as": "",
    "vokal.o": "",
    "vol.as": "",
    "volumin.o": "volumeno",
    "volunt.as (netr)": "volonte ... -as, volontas",
    "volv.as": "",
    "vort.o": "",
    "vot.as (tr/netr)": "voĉdonas",
    "voy.o": "vojo",
    "voyaj.as (netr)": "vojaĝas",
    "vu": "vi (singulara)",
    "vu.a": "via (singulare)",
    "vulgar.a": "",
    "vund.as": "",
    "west.o": "okcidento",
    "ya": "ja",
    "yar.o": "jaro",
    "ye": "je",
    "yen": "jen",
    "yes": "jes",
    "yun.a": "juna",
    "yun.in.o": "junulino",
    "yun.o": "junul(in)o",
    "yun.ul.o": "junulo",
    "yur.o": "rajto",
    "yust.a": "justa",
    "zer.o": "nulo",
    "zon.o": ""
};
//# sourceMappingURL=vortaro.js.map